### ISSUE TITLE
Record and Replay Utilities

### ISSUE THREAD

**Issue by sid5291** [continental/ecal#13]
Hi eCAL Team,

I have been using eCAL for a couple of days now transitioning over from a flavor of DDS. This project is great and apart from the great performance boost, I really like the monitoring tool.

I had a couple of requests/ questions:
1. As the title mentions I see that there is mention of this in the docs, so I was wondering is there a plan to have a Record and Replay utility ? It was something that was very handy when i was using DDS.

2. I was wondering if you could maybe either add to the docs or point me in the correct direction on how i would add a different serialization format to the monitoring tool ...like say capnproto ? 

Thank You

**Comment by FlorianReimold** [comment]
>     1. As the title mentions I see that there is mention of this in the docs, so I was wondering is there a plan to have a Record and Replay utility ? It was something that was very handy when i was using DDS.

The record and replay utility are currently under development. We hope that we can release those in August or September. Both will come in GUI and CLI flavour.

**Comment by rex-schilasky** [comment]
Yes, like @FlorianReimold  mentioned both functionalities are short before release, we use them internally for a couple of years now. As measurement container format we use [HDF5](https://www.hdfgroup.org/solutions/hdf5/). 
Recording can be done distributed over multiple hosts. A c++ / python API can be used to post process the data, a command line and Qt GUI app to replay them.

Regarding the implementation of another serialization format to the monitoring tool. The monitor has a plugin interface to add any kind of visualization for different eCAL message types. You can find 4 existing implementations here https://github.com/continental/ecal/tree/master/app/mon/eCALMonPlugins.
To support capnproto you can use the protobuf plugin as a template. Finally the tricky part is to understand and use the capnproto reflection API to get the "live data preview" working.

We are working on a better documentation, that will include the documentation for the eCALMon plugin API.

**Comment by sid5291** [comment]
Thank You @rex-schilasky and @FlorianReimold . I look forward to the release of the Record and Replay utility.. Also would be happy to help with testing if needed I am running eCal on an x86 and ARMv8 platform..

Thank you for pointing me to the eCALMonPlugins, I will try to implement a plugin for capnproto and see how far I get.

**Comment by rex-schilasky** [comment]
@sid5291 thank you for providing support in testing eCAL. Regarding the capnproto eCALMon plugin I talked with @Kerstin-Keller and this plugin is realized yet and can be published with one of the next releases. So don’t invest some effort here ...

**Comment by sid5291** [comment]
@rex-schilasky Thank you! Then I will continue to use protobufs till the change is incorporated

**Comment by rex-schilasky** [comment]
CapnProto monitor reflection plugin is released with eCAL5.4.0.

**Comment by sid5291** [comment]
Thank You @rex-schilasky  will start testing it out. !
