### ISSUE TITLE
CMake config error with ECAL_THIRDPARTY_BUILD_TINYXML2=OFF

### ISSUE THREAD

**Issue by pablorcum** [continental/ecal#150]
The following error occurs after trying to build eCAL with `ECAL_THIRDPARTY_BUILD_TINYXML2=OFF` with the commit cfdfcd2a852bfb2dcc934d40f99209026bc955f7. In previous versions, it used to work fine. The workaround is to set ECAL_THIRDPARTY_BUILD_TINYXML2 to on or leave it by default.

    CMake Error at CMakeLists.txt:284 (_find_package):
      By not providing "Findtinyxml2.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "tinyxml2",
      but CMake did not find one.

    tinyxml2Config.cmake
    tinyxml2-config.cmake

      Add the installation prefix of "tinyxml2" to CMAKE_PREFIX_PATH or set
     "tinyxml2_DIR" to a directory containing one of the above files.  If
     "tinyxml2" provides a separate development package or SDK, be sure it has
     been installed.
    Call Stack (most recent call first):
      app/sys/sys_core/CMakeLists.txt:24 (find_package)

    -- Configuring incomplete, errors occurred!

**Comment by hannemn** [comment]
Hello @pablorcum, since the last minor version update of ecal, there is a new component  called ecal_sys which requires tinyxml and is also part of the QNX build (if BUILD_APPS=ON). Because of this circumstance please leave ECAL_THIRDPARTY_BUILD_TINYXML2 on enabled as it is by default.
