### ISSUE TITLE
Build ecal_process for QNX fails due to missing argument_vector declaration

### ISSUE THREAD

**Issue by pablorcum** [continental/ecal#151]
In the elif block for ECAL_OS_QNX at line 961 of ecal_process.cpp, there is a missing declaration for argument_vector, `std::vector<std::string> argument_vector;` as it appears in every other case. Please add that missing line under `g_process_par = "";`.

**Comment by pablorcum** [comment]
@hannemn Please look into this for the qnx-compatibility branch.

**Comment by hannemn** [comment]
Has been fixed with 07cfc34265680bf30e18316c9338f07f29c2bf2d .
