### ISSUE TITLE
error saving channel name mapping if splitted hdf5 file is opened 

### ISSUE THREAD

**Issue by slinshady89** [continental/ecal#152]
![image](https://user-images.githubusercontent.com/28022813/103649377-a0e7d480-4f5e-11eb-9a7b-1f32e1f4015c.png)

if I collect a long measurement which gets splitted into several the player shows the following error if I open a single hdf5 file the channel mapping can't be saved.

**Comment by FlorianReimold** [comment]
This has been "accidentally" fixed at some point, probably when I implemented support for opening `.ecalmeas` files. I will close this issue. Please reopen, if you somehow manage to reproduce the issue with a recent eCAL Version 😉
