### ISSUE TITLE
Memory bug in contrib/ecalhdf5/src/eh5_meas_dir.cpp

### ISSUE THREAD

**Issue by ZobyTwo** [continental/ecal#153]
Hey there,

in `contrib/ecalhdf5/src/eh5_meas_dir.cpp`, in the second ctor (line 52), you should set `access_` (to `RDONLY`) so that the nested call to `Close`() does not read from uninitialized memory.

**Comment by FlorianReimold** [comment]
Hey, thanks for pointing that out! I will check (and fix) that!
