### ISSUE TITLE
Getting Started Python Tutorial from Scratch

### ISSUE THREAD

**Issue by jldk20** [continental/ecal#158]
Hi, could you please provide a step-by-step python tutorial for creating custom protobuf messages and receiving them. I just need a minimal example/ a list of the steps if have to do, to get the full pipeline functional. Here are some background informations: I want to implement a camera supervision for my house entrance. Therefor i currently use a Jetson Nano and a Webcam. The desired achievement is to receive the webcam image, as well as some structured metadata on the host pc inside the house. The message should be structured similar as follows:
Entrance (Topic)
....|-Image
....|-ImgInfo
..........|-Width
..........|-Height
..........|-IsColored
....|-DeviceInfo
....|-EnvInfo
..........|-Date
..........|-(Numpy-Array of various helpful information)
 
It would be very kind if you have the time to help me.

**Comment by FlorianReimold** [comment]
Hey, these sample should get you started:

person_snd:
https://github.com/continental/ecal/blob/master/samples/python/person_snd/person_snd.py

person_rec:
https://github.com/continental/ecal/blob/master/samples/python/person_rec/person_rec.py

The proto files for the samples are located in the `../_protobuf` directory. When you write your own .proto files, you must of course first compile the python representation for those:
```
protoc -I=$SRC_DIR --python_out=$DST_DIR $SRC_DIR/your_proto_file.proto
```
(Source: https://developers.google.com/protocol-buffers/docs/pythontutorial#compiling-your-protocol-buffers)

To get started writing .proto files, you may want to look at the proto3 tutorial:
https://developers.google.com/protocol-buffers/docs/proto3

The syntax of Protobuf is quite simple, you only have  a few primitive datatypes (`bool`, `int32`, `double`...). If you want to create a more complex datatype, you basically define another `message` and use it as datatype. To create arrays, you use the `repeated` keyword

``` proto
message SearchResponse {
  repeated Result results = 1;
}

message Result {
  string url = 1;
  string title = 2;
  repeated string snippets = 3;
}
```
(Source: https://developers.google.com/protocol-buffers/docs/proto3#other)

**Comment by jldk20** [comment]
Thank you very much for the detailed description and the very useful references!!! It works pretty fine 🥇
