### ISSUE TITLE
cmake does not find QT5

### ISSUE THREAD

**Issue by AntoineBassoul** [continental/ecal#170]
Hi,

I had issues trying to create an ecal setup from source : 
cmake would not find the QT find script, could solve the issue by manually adding set(Qt5_DIR C:/Qt/5.15.2/msvc2019_64/lib/cmake/Qt5) to the main CMakeLists.

Generating for VS2019 : win_make_cmake.bat v142
Content of QT5_ROOT_DIRECTORY: 
![image](https://user-images.githubusercontent.com/45589077/106392854-14f98900-63f4-11eb-9701-67adbdf64385.png)
The recommended binaries are not present because most of them are not available anymore from the QT installer (msvc2015 32-bit or msvc2015 64-bit (VS2015) or msvc2017 32-bit and msvc2017 64-bit (VS2017)), so I thought I'd give a try with only msvc2019 64bit.

Cheers !

**Comment by FlorianReimold** [comment]
You are right, the batch files only work properly for VS 2015 and 2017. We implemented a fancy custom Qt find method to support 32 and 64 bit Windows configurations simultaneously (hence the note to download both configurations). But although eCAL still compiles in 32bit, our standard configuration is pure Win64 and therefore the 32bit Qt libraries won't even get used.

So here is a pretty easy way to get it working with VS 2019 and any Qt Version by setting the `CMAKE_PREFIX_PATH`:

```bat
set "CMAKE_PREFIX_PATH=C:/Qt/5.15.2/msvc2019_64"
call build_win\win_make_cmake.bat v142
```

Maybe I should just replace the QT_ROOT_DIRECTORY with the CMAKE_PREFIX_PATH method, as the latter will never get outdated.
