### ISSUE TITLE
Project does not build with imported protoc target

### ISSUE THREAD

**Issue by pablorcum** [continental/ecal#187]
Crosscompiling eCAL may required importing the protoc target for the current host. Due to the recent additions to disable warnings for third-party lib in the main CMakeLists.txt, the eCAL build is broken for crosscompiling targets such as QNX.

Please edit the following code in the main CMakeLists.txt lines 143-146.

    target_compile_options(protoc PRIVATE
      $<$<CXX_COMPILER_ID:MSVC>:/W0>
      $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-w>
    )

to include an if statement that checks the IMPORTED_LOCATION as shown below.

    if (protobuf_BUILD_PROTOC_BINARIES)
      target_compile_options(protoc PRIVATE
        $<$<CXX_COMPILER_ID:MSVC>:/W0>
        $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-w>
      )
    endif()

**Comment by FlorianReimold** [comment]
Hi Pablo,

I tried solving that issue in a more generic way, as I was afraid it would not only be an issue with protobuf, but with any library that one would import from another location. Thus I moved the warning-disabling-code into the ``if (NOT TARGET ...)`` statement. Can you check it out and give me feedback, if my chosen solution works for your crosscompile build?

Branch: https://github.com/continental/ecal/compare/hotfix/crosscompile_fix
Commit: https://github.com/continental/ecal/commit/42aeec58040efd3ed876d96b17bd3ee6b409c240

Regards
Florian

**Comment by pablorcum** [comment]
Hi Florian, thanks for the quick fix. Unfortunately, it is still not working. I have the following configuration in my CMake toolchain file.

```
# Set protoc properties for cross-compiling
add_executable(protoc IMPORTED)
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	set_target_properties(protoc PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/../protoc-3.11.4-win64/bin/protoc.exe)
else()
	set_target_properties(protoc PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/../protoc-3.11.4-linux-x86_64/bin/protoc)
endif()
set_target_properties(protoc PROPERTIES IMPORTED_GLOBAL TRUE)
```

**Comment by FlorianReimold** [comment]
Thanks for the Feedback! I have comitted another attempt, wich does not disable warnings for imported targets. This should fix the crosscompile build. Please give me feedback if it works as intended! :)

Commit: 217c22cf6a07cf40130c2bd0eccd522db8257b36

**Comment by pablorcum** [comment]
Now, it is working well. Thank you!
