### ISSUE TITLE
eCALPlayer: Hangs when trying to access non-existant measurement

### ISSUE THREAD

**Issue by julien-seitz** [continental/ecal#193]
**Describe the bug**
When trying to open an non-existent measurement via "File" -> "Recent Measurements" -> 
the Graphical User Interface hangs.

**To Reproduce**
- Open a measurement in eCALPlayer
- Close the eCALPlayer
- Delete the measurement or move it to another location
- Reopen eCALPlayer
- Try to open the measurement via "File" -> "Recent Measurements" -> 

**Expected behavior**
An error message that the measurement does not exist any longer

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS:Windows
 - Version:eCAL 5.7.2

**Comment by FlorianReimold** [comment]
I can confirm the issue. It is caused when the deleted measurement was loaded from a directory (not an .ecalmeas file). In that case, the eCAL Player will try to load the parent directory, which will probably contain many files. This may take very long and look like the player is freezing.
