### ISSUE TITLE
eCALPlayer: Reset "limit playback range" when changing the measurement

### ISSUE THREAD

**Issue by julien-seitz** [continental/ecal#194]
**Describe the bug**
The playback range does not get resetted when the measurement is changed.
If the second measurement is shorter than the first one, then it's not possible to change the playback range

**To Reproduce**
- Open a measurement
- Change the replay range
- Open another measurement

**Expected behavior**
Playback Range should be resetted

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS:Windows
 - Version:eCAL 5.7.2

**Comment by FlorianReimold** [comment]
Already fixed in eCAL [5.7.8](https://github.com/continental/ecal/releases/tag/v5.7.8) and [5.8.3](https://github.com/continental/ecal/releases/tag/v5.8.3). Please upgrade your eCAL installation to something newer than 5.7.2 😉
