### ISSUE TITLE
Protobuf 3.15.3 issues

### ISSUE THREAD

**Issue by FlorianReimold** [continental/ecal#199]
eCAL seems to have issues with Protobuf 3.15.3.

The issue was brought up by the macOS Build. When the build machines used Protobuf 3.14.0 everything was fine, but when Homebrew updated to Protobuf 3.15.3 eCAL failed to build on macOS.

Build log: https://github.com/continental/ecal/runs/2029358598?check_suite_focus=true

I have confirmed that the same issue occurs on Windows, when updating the protobuf submodule to 3.15.3.

**Comment by rex-schilasky** [comment]
To use package name pb seems to be problematic in the newer version. Like in this protobuf definition
```proto
package pb.People;

message Person
{
  enum SType
  {
    MALE   = 0;
    FEMALE = 1;
  }

  int32  id               = 1;
  string name             = 2;
  SType  stype            = 3;
  string email            = 4;

  Animal.Dog        dog   = 5;
  Environment.House house = 6;
}

```

**Comment by FlorianReimold** [comment]
Fixed in master. eCAL 5.8 and 5.7 will stay on the old sample (and old protobuf). When not building the samples, eCAL 5.7 / 5.8 can even be built with Protobuf 3.15.
