### ISSUE TITLE
Is there a linux version available or is it in future plan?

### ISSUE THREAD

**Issue by Capri2014** [continental/ecal#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by floriangeis** [comment]
Hello @Capri2014, there so many different Linux versions for different platforms, we cannot provide eCAL binaries for every combination. My suggestion: Read the build instructions in the [readme.md](https://github.com/continental/ecal/blob/master/README.md) (section: Setup on Linux Systems) and build eCAL exaclty for your linux version on your target, so it will perfectly match your needs.

**Comment by Capri2014** [comment]
thanks!
