### ISSUE TITLE
Samples are not building with default cmake command

### ISSUE THREAD

**Issue by floriangeis** [continental/ecal#201]
If a user has installed eCAL from a released installer, it is not possible to cmake + build the eCAL samples that use protobuf (e.g. person send). Problem seems to be the style how protobuf library will be linked by default. 

This happens for windows only

Possible solution: 
Like it is done in the hello-world example, there shall be a cmake command, like this:
![image](https://user-images.githubusercontent.com/45308813/109978977-b2e7b880-7cfe-11eb-86f9-ed34b193ef5d.png)

**Comment by KerstinKeller** [comment]
Btw, also tclap cannot be found, needed by latency_send sample
```
CMake Error at cpp/latency/latency_snd/CMakeLists.txt:22 (find_package):
  By not providing "Findtclap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "tclap", but
  CMake did not find one.

  Could not find a package configuration file provided by "tclap" with any of
  the following names:

    tclapConfig.cmake
    tclap-config.cmake
```

**Comment by KerstinKeller** [comment]
With newer CMake version, you also need a mandatory `cmake_minimum_required(VERSION 3.??)` on top of every top-level CMake file, which is not present in `samples/CMakeLists.txt`.

**Comment by KerstinKeller** [comment]
When building the samples with `-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON` it builds. I think this should be enabled, by default, and always, but I am not sure if it has implications on the eCAL build itself.
If not, we can set in in the samples CMakeLists.txt file.
