### ISSUE TITLE
build fails on RPI/arm 

### ISSUE THREAD

**Issue by albertxos** [continental/ecal#207]
Description:

Build fails on Target:

- PI 3 Model B Rev 1.2
- Raspian 10 with Kernel 5.4.51-v7+
- ecal 5.8  https://github.com/continental/ecal/releases/tag/v5.7.8

How to reproduce:
Follow https://continental.github.io/ecal/development/building_ecal_from_source.html

1.  mkdir _build 
2. cd _build
3.  cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCS=OFF
4.  make -j4

Result:
![image](https://user-images.githubusercontent.com/31403401/110303583-d5c5e580-7ffa-11eb-8206-2477dd40206f.png)

Expected: 
Successful build

Solution:
Add flag in ecal/CMakeList.txt for ARM/RPI Targets:
`set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")`

**Comment by FlorianReimold** [comment]
Hey albert,

Unfortunatelly I cannot reproduce that issue. The launchpad build farm compiles eCAL for Ubuntu 16.04 / 18.04 / 20.04 / 20.10 on both arm64 and armhf without any issue. The ppa with the artifacts can be found [here](https://launchpad.net/~ecal/+archive/ubuntu/ecal-latest/). The built is done on native arm machines running the according operating system (so there is no cross-compile involved).

I have done a little bit of research. According to [this issue](https://gitlab.kitware.com/cmake/cmake/-/issues/21174), the `-latomic`flag is only needed on some 32bit arm and risc-v platforms and should not be added for all plattforms. They suggest trying to compile an test program to check whether `libatomic` is needed.

**Comment by albertxos** [comment]
Hey Florian,

I've used a raspberry (arm32), maybe it is only reproduceable on that device?

**Comment by FlorianReimold** [comment]
Probably, yes. The issue is a 32 bit issue when using 64bit atomic datatypes (if I understood it correctly). It only occurs on certian architectures using certain compilers that don't detect the issue by themselfes.

Maybe we can use the code from WebKit. They had the same problem and implemented a compile-check whether libatomic is needed.
https://github.com/WebKit/WebKit/blob/88278b55563e5ccdc0b3419c6c391c3becc19e40/Source/cmake/WebKitCompilerFlags.cmake#L274

**Comment by FlorianReimold** [comment]
I stripped down the WebKit solution and integrated a similar approach into eCAL. The code is in the [feature/libatomic](https://github.com/continental/ecal/tree/feature/libatomic) branch. I didn't have any chance to test it. Can you give it a try and check if it solves the problem for you?

**Comment by albertxos** [comment]
https://github.com/continental/ecal/commit/09d8f04a483052acc88bb4451789761e13d1305b seems to work now!
Thank you for the fast fix
