### ISSUE TITLE
eCalRec: Jump to recording

### ISSUE THREAD

**Issue by julien-seitz** [continental/ecal#218]
It would be a nice feature if there would be an option to directly jump to the folder of a newly created measurement in eCALRec (with windows explorer or a corresponding file explorer on linux)
Maybe via a button or via a context menu. Quite often I create recordings on my PC and typically the next step I need to do is to find the corresponding folder in the file browser.

If that is not that easy, it would be helpful to copy the path to the measurement to the clipboard.

Thanks

**Comment by FlorianReimold** [comment]
Good idea, I have had that on my roadmap for quite some time now and never found time to implement it ;)
