### ISSUE TITLE
eCAL Player: Add information about size of each channel

### ISSUE THREAD

**Issue by julien-seitz** [continental/ecal#228]
**Is your feature request related to a problem? Please describe.**
It would be nice to get a rough estimation about the size of an topic directly in eCAL Player.
Quite often I have to deal with big recordings and actually I just need a small subset of it.
Typically I then check the amount of frames in eCALPlayer and combine it with the topic size in eCALMonitor to get a rough estimation. However this causes quite some effort

**Describe the solution you'd like**
Directly show the total size of a topic in eCALPlayer.

**Comment by FlorianReimold** [comment]
Hi Julien,

I am not really sure what your use-case is. What do you gain from knowing how large a channel is? The measurement will not reduce in size from knowing this, so I wonder what you do with that information.

**Comment by julien-seitz** [comment]
Hi Florian,
The use-case is that my next processing step typically is to remove the biggest channels from the recordings (as they are in most cases not relevant for me) or to disable them during replay. It might happen that the replay of all channels at the same time is too slow on my local machine and I have to restrict it to the required channels to achieve realtime-performance.

**Comment by rex-schilasky** [comment]
Hi Julien, but channels that are unsubscribed should not cause any performance needs because they are not send. Did you really notice performance decrease by playing unsubcribed channels ?

**Comment by julien-seitz** [comment]
Hello Rex, thanks for the Hint.
Yes you are right. Channels that are not received do not cause any negative performance impact. I just checked that.
I think I might have experienced negative effects with quite old versions of eCALPlayer and kept the attitude to deselect big channels since then.

However, retrieving information about the Channel-Size in a recording anyhow would be helpful. Typically, I do extract the relevant channels from a recording to the bare minimum that I need to analyzation purposes. Quite often I can reduce the measurements to 3-5% of the original size (depending on the use-case and project). This allows me to store them locally.

Additionally, we quite often have the situation that overall measurements size or bandwidth consumption should be reduced. For this purpose it's very helpful to know what channels do typically cause the most traffic. eCALMon and the eCALMon XML Nodes Export provide some hints, but they typically just show a instantaneous snapshot and do not cover a whole recording.

Maybe eCALConv might be a suitable place aswell to display that information or a small command line application could be helpful.

**Comment by julien-seitz** [comment]
Update: I just used the eCAL Python API to retrieve the information of the channel-size from a recording.
That is absolutely sufficient for me.
It might also be difficult to integrate that functionality into the Player because I think it is required to parse the whole recording to retrieve this information. That might result in additional delays when opening a recording.
