### ISSUE TITLE
Python Service Example does not work

### ISSUE THREAD

**Issue by JeremyBYU** [continental/ecal#244]
The [Python simple service](https://github.com/continental/ecal/tree/master/samples/python/minimal_service) example does not work. The example is an integrated server and client example. The program hangs/is-stuck when the client tries to call the server on line 76: https://github.com/continental/ecal/blob/master/samples/python/minimal_service/minimal_service.py#L76

```
(realsense) ➜  realsense-tracking git:(master) ✗ python -m scripts.scratch.minimal_service
eCAL v5.8.5 (18.03.2021)

'DemoService' method 'foo' requested with : b'hello foo 1'
```

This might be because Python is single threaded and it cant handle being a server and client in the way ECAL is currently structured for python bindings? Note this [example](https://github.com/continental/ecal/issues/39#issuecomment-578141502) I posted a while back still works as expected. It splits the sever and client into two files and two separate python processes. 

On a totally different note:
I will be trying to create an ECAL server as well as having ECAL subscriber in the same python process soon. I'm wondering how ECAL is handling threading for these purposes and if everything will work out of the box. Wondering if its all on the same thread (with GIL), 2 threads, or even more. And if proper [threading](https://docs.python.org/3/library/threading.html#threading.Lock) or [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#synchronization-between-processes) locks will work to synchronize between them. I'll try it and see how it goes.

**Comment by rex-schilasky** [comment]
Thank you for reporting Jeremy. I could reproduce this issue and I assume that this deadlock is based on the mentioned GIL, a Global Interpreter (Dead)Lock so to say .. I will check what we can do here.

**Comment by JeremyBYU** [comment]
FYI from my initial experiments:

ECAL only spawns separate threads, not processes. Upon initialization ( no service , no subscribers) I saw three threads when looking on 'htop'. 

When adding 1 or more subscribers it will spawn another thread. However this thread will NOT deadlock with the main thread. I mean this in quite the literal way. I tested this with a high computation and full blocking while loop and the main thread was free to continue. However if any one subscriber has a high workload it will block. This means ECAL had spawned a GIL free thread for subscribers. 

Next I launched a service and with callbacks. Once again a nother new thread  was created that was sperate form all the others ( now a total of 5 threads). Tested the same way and found it GIL free as well. However all services seem to be on this one thread. I assume that maybe clients are too but I have not verified that.

I also noticed that python defaults to UDP multicast, not shared memory. Is it possible to used shared memory with Python? Probably a tall order....

**Comment by rex-schilasky** [comment]
Hi Jeremy, regarding the transport eCAL is using the same layers for C, C++, C#, Python for the data transport. You can check this in the monitor. Additional to the transport layer all eCAL applications always share some monitoring information via UDP multicast.

![image](https://user-images.githubusercontent.com/49162693/113307278-42d05080-9305-11eb-8832-b42f7ccca6cb.png)

**Comment by JeremyBYU** [comment]
Hmm that did not seem to be working for me. I have two C++ programs (RSPub, and RSIntegrate), one producing and one consuming topic RBGDMessage. I start them up and they are working with shared memory as shown in ECAL monitor. RSPub is also publishing a PoseMessage and DepthMessage but no one is subscribing yet.

![image](https://user-images.githubusercontent.com/6628085/113312295-25d15880-92d8-11eb-9725-3ed9874edcf4.png)

Then I launched the python program, which subscribes to the PoseMessage and the same RGBDMessage. However it shows UDP multicast:

![image](https://user-images.githubusercontent.com/6628085/113312654-81034b00-92d8-11eb-86fd-d63ee214e2db.png)

Maybe I am missing a step?

**Comment by rex-schilasky** [comment]
Do they all run on the same physical machine without any kind of container or VM ?

**Comment by JeremyBYU** [comment]
The two C++ programs are running inside of a container with full access and
shared memory to host. ECAL monitor is running directly on the host machine
and is able to get shared memory access when subscribing to topics. The
python program is running directly on the host machine but only gets UDP
multicast. I can try putting the python program in the container and seeing
if the issue persists (containers shared memory is already working).

**Comment by rex-schilasky** [comment]
This is really strange. And the monitor (running on the same machine like the python script) is using shared memory when you subscribing a message by double clicking on it ?

**Comment by JeremyBYU** [comment]
I  just tried to verify that ecal_mon_gui subscribes with shared memory.  It is not working anymore, it is using udp_multicast. However it was definitely working before so let me see if I changed something and get back to you on that.  I also just `rm -rf ~` my home directory 1 hour ago accidentally and have spent the time trying to get back up to speed.

**Comment by rex-schilasky** [comment]
So it seems to me that there is a "general misunderstanding" between your container and the host and eCAL switches back to udp. Hope you can reconfigure all and get it run. To be honest I'm not playing with such containers that much. So your findings will be helpful for us. The good news is .. eCAL messages always find a way to flow from one to another :).

**Comment by JeremyBYU** [comment]
Well I havent figured it all out but its good enough for now. I have multiple computers. My desktop computer (linux 18.04) is fully working and can run docker containers with shared memory on the host and between containers. It can broadcast UDP messages and it will work with all other computers on the network. Its rock solid and working as expected. Also I tested the python program running on the host, and it worked just fine receiving shared memory form docker container.

I have another laptop connected to the same network (linux ubuntu 20.04). It can see messages just fine broadcasted from the desktop docker containers. However I also wanted to see if it could run the docker containers itself and if it would work. So basically I downloaded the docker containers, configured the network, and run the same docker-compose file. However it is not working. When running ECAL mon gui it can see the processes but can not access the data. I can even see the shared memory files being created on the host computer under `/dev/shm`. However, I think this is good enough for now so I am not going to worry about it. In the end, the laptops purpose will be to receive messages from a different computer running docker containers. 

Anyways, this issue got pretty sidetracked. You can close it whenever you want or when you get the Python service example working.  Thank!

**Comment by rex-schilasky** [comment]
For now I changed the service implementation into two separate units. See new [minimal service sample](https://github.com/continental/ecal/tree/hotfix/python_service_sample_gil/samples/python/minimal_service).
