### ISSUE TITLE
eCAL samples over network

### ISSUE THREAD

**Issue by StudentK001** [continental/ecal#253]
Hi,
I am trying to connect two RPIs running on ubuntu 20.10 operating system. After following the same instructions as mentioned on following link:
[https://continental.github.io/ecal/getting_started/cloud.html](https://continental.github.io/ecal/getting_started/cloud.html)
I can see the network is configured:
![Screenshot from 2021-04-21 14-51-37](https://user-images.githubusercontent.com/48187918/115551016-2e072d00-a2b3-11eb-859f-37bed7c7ab88.png)
However, I get this error and the devices do no connect.
`shm_open failed : /person_5729184297_shm errno: No such file or directory`

I'm unable to figureout what is going wrong

Thanks in advance!
Regards,
Kanwal

**Comment by rex-schilasky** [comment]
Did you name the two hosts differently ? That is important for the decision of the ecal core to transfer payload via shared memory (same host name for the publisher and the subscriber) or via udp (publisher / subscriber are running on two different hosts).

**Comment by StudentK001** [comment]
The hostnames are same.

**Comment by rex-schilasky** [comment]
So please rename one of them if this is possible.

**Comment by StudentK001** [comment]
Awesome, Thank you very much it worked :)

**Comment by rex-schilasky** [comment]
You are welcome, good luck with your project, ReX
