### ISSUE TITLE
Support arm64 cross-compile?

### ISSUE THREAD

**Issue by christopherbate** [continental/ecal#256]
**Is your feature request related to a problem? Please describe.**
It would be great if there were an example cross compilation (to ARM64) CMake toolchain file and/or a simple QEMU/docker based test for it. I'm having to make many modifications to the CMakeLists to support a cross compilation scenario that should be fairly straightforward. eCAL has been more frustrating that other CMake projects to get this working (in my experience). It's mostly small things needed to be tweaked in CMakeLists's, for example

-  `find_path` statements for internal dependencies (`cmake/Modules/...`) not playing nicely with common `CMAKE_FIND_ROOT_PATH` settings usually present in CMake toolchain files. CMake will direct those kinds of `find_...` calls to only search within a specific sysroot folders depending on `CMAKE_FIND_ROOT_PATH` calls. For whatever reason, the `find_path` calls won't find the internal dependency paths unless the calls are annotated with `NO_DEFAULT_PATH` and `NO_CMAKE_FIND_ROOT_PATH`.

I expect a simple cross compile testing setup like the tools [here](https://github.com/dockcross/dockcross), would flush out most of these small details.

For many people in automotive or industrial robotics I'm sure compile natively for their target is not an option, so it would help with adoption if this process were more straightforward. 

I can submit issues I've fixed like the one above in a separate issue

**Comment by FlorianReimold** [comment]
Hi Chris,

I have no experience with cross compilation, as we compile our Ubuntu arm64 builds natively on arm64 machines. So it would be very helpfull if you could share your modifications that you had to make to get it cross compiling!

**Comment by christopherbate** [comment]
sounds good. I have a small test suite I put together which I'm about to PR

**Comment by christopherbate** [comment]
Close due to #257
