### ISSUE TITLE
protobuf dependency not installed on Ubuntu 20.04 when using apt repo

### ISSUE THREAD

**Issue by webera** [continental/ecal#259]
**Whats the issue**
Nothing serious but it would be of course nice to have all dependencies installed to build software requiring ecal. When installing ecal following the doc from here https://continental.github.io/ecal/getting_started/setup.html it says for 5.8

```
sudo add-apt-repository ppa:ecal/ecal-5.8
sudo apt-get update
sudo apt-get install ecal
```

protobuf dependencies are not installed at least when using Ubuntu 20.04.

**To Reproduce**

```
$ docker run -it --net=host ros:foxy
# cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

# apt update && apt install -y software-properties-common
# add-apt-repository ppa:ecal/ecal-5.8 && apt install -y ecal
# cd /tmp && git clone https://github.com/continental/ecal
# cd /tmp/ecal/samples/cpp/pingpong/ping
# mkdir build && cd build
# cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:624 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /usr/lib/x86_64-linux-gnu/cmake/eCAL/eCALConfig.cmake:67 (find_package)
  CMakeLists.txt:25 (find_package)
```

**Expected behavior**
```
...
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1")
...
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ecal/samples/cpp/pingpong/ping/build
```

**Desktop**
 - OS: Ubuntu
 - Version Ubuntu 20.04.2 LTS

**Further context**

Simple fix is of course `apt install libprotobuf-dev`.
If the `ecal` package should just be the library and no dev-stuff I would suggest to have a `ecal-dev` package which can be installed and then has the proper dependencies.

Best,
Antonio

**Comment by FlorianReimold** [comment]
Thanks, I will keep that in mind for the future.

At the moment, we only ship that "fat debian installer" through the PPA, which includes the runtime, all apps, samples and all dev files. The dependencies however are runtime dependencies only, as you may not alway want to install dev packages to run your eCAL based software.
In the future (maybe for 5.9) we want to improve the installer and split up the `ecal` package into proper smaller packages. Then we will also have an `libecal-dev` package that can depend on `libprotobuf-dev`.

Regards
Florian

**Comment by webera** [comment]
Ah perfect, that sounds good!
