### ISSUE TITLE
Unable to start eCAL-Player or eCAL-Record missing shared libraries: libhdf5.so.103

### ISSUE THREAD

**Issue by aserbremen** [continental/ecal#26]
**Describe the bug**
When typing `ecal_play` into the console I receive following following error:
 `ecal_play: error while loading shared libraries: libhdf5.so.103: cannot open shared object file: No such file or directory`

**To Reproduce**
Installed eCAL according to github page install instructions on Ubuntu 18.04. I am able to start eCAL-Monitor

**Additional context**
Output of `apt list libhdf5-dev`:
`Listing... Done
libhdf5-dev/bionic,now 1.10.0-patch1+docs-4 amd64 [installed]`

Output of `ls /usr/local/lib/libecal*`:
`/usr/local/lib/libecal_core_c.so`
`/usr/local/lib/libecal_core.so`
`/local/lib/libecal_EcalUtils.a`
`/local/lib/libecal_pb.a`
`/local/lib/libecaltime-localtime.so`
`/usr/local/lib/libecal_core_c.so.5`
`/local/lib/libecal_core.so.5`
`/local/lib/libecal_hdf5.a`
`/local/lib/libecal_proto.a`
`/local/lib/libecaltime-simtime.so`
`/usr/local/lib/libecal_core_c.so.5.5.0`
`/usr/local/lib/libecal_core.so.5.5.0`
`/usr/local/lib/libecal_mon_plugin_lib.a`
`/usr/local/lib/libecaltime-linuxptp.so`

**Comment by rex-schilasky** [comment]
I did the same on a "naked" Ubuntu 18.04 and ecaL_play is working well. I made a 'ldd' and the output is
![image](https://user-images.githubusercontent.com/49162693/68403441-392cd280-017d-11ea-9f62-ae9c8fc00ac8.png)

**Comment by aserbremen** [comment]
Indeed I don't have a link to libhdf5.so.103

![image](https://user-images.githubusercontent.com/56029245/68404308-9d9c6180-017e-11ea-988b-a501af76c005.png)

This is the tab competion listing for `libhdf5_`

![image](https://user-images.githubusercontent.com/56029245/68404620-23b8a800-017f-11ea-90d1-edb397d624a3.png)

Could you tell me how to correctly link the right library? I noticed that my installation tries to link `libhdf5.so.103` whereas Yours `libhdf5_serial.so.100`. I am not sure about the exact impact of the different library names and numbers. Moreover I do not have the exact `libhdf5.so.103` listed under `/usr/lib/x86_64-linux-gnu/`

**Comment by aserbremen** [comment]
Indeed I could find `libhdf5.so.103` on my system. It is part of the anaconda python installation: 
![image](https://user-images.githubusercontent.com/56029245/68463493-0f23f080-020f-11ea-8ad3-341a1f962d97.png)

This might be a bit overkill, but here are the lines containing`HDF5` in the `CMakeCache.txt` 
![image](https://user-images.githubusercontent.com/56029245/68463741-9f623580-020f-11ea-88bc-0f83f62b2898.png)

What would be the best approach to tackela this problem? Manually link the library? Rebuild eCAL in a different way?

**Comment by Kerstin-Keller** [comment]
Please remove your build folder completely and then rebuild eCAL.
Please also pass `-DHDF5_ROOT=/usr` when calling cmake, thus calling
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF -DHDF5_ROOT=/usr
``` 
I would assume that it will then find the HDF5 version installed in your system (or at least I'd hope so).

Alternatively, you could add `home/serov/anaconda3/lib` to your `LD_LIBRARY_PATH` and use the anaconda hdf5 library at runtime.

**Comment by aserbremen** [comment]
> Please remove your build folder completely and then rebuild eCAL.
> Please also pass `-DHDF5_ROOT=/usr` when calling cmake, thus calling

This helped me remove the wrong linkage of `libhdf5.so.103` from the anaconda environment however cmake tried to link other libraries to the anaconda path.

I resolved the wrong linkage of libraries by temorarily removing all unwanted folders from `PATH`  before configuring eCAL with `cmake ..` (described here https://gitlab.com/morpheus.lab/morpheus/issues/3):
`echo $PATH`
`/opt/ros/melodic/bin:/home/serov/anaconda3/bin:/home/serov/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

and then exporting `PATH` without any unwanted folders, in my case `/home/serov/anaconda3/bin` and  `/home/serov/anaconda3/condabin`:
`export PATH="/opt/ros/melodic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"`

After that I was able to succesfully configure and build eCAL and run `ecal_play` or `ecal_rec`.

**Comment by Kerstin-Keller** [comment]
Ok, good to hear that it is working for you now 😄
