### ISSUE TITLE
doc page is broken

### ISSUE THREAD

**Issue by fei4xu** [continental/ecal#267]
Hi,

I'm reading the doc but it seems that there is a broken page:

https://continental.github.io/ecal/_api/function_ecal__core_8h_1a390408819d676df7778dc77934dcd7eb.html#exhale-function-ecal-core-8h-1a390408819d676df7778dc77934dcd7eb

**Comment by FlorianReimold** [comment]
Yep, thanks for pointing that out. It is causes by having both the C and C++ API in one header file (I guess). Thus Doxygen is unable to differentiate between both.

**Comment by FlorianReimold** [comment]
Closing this, because it magically got fixed somehow😄
