### ISSUE TITLE
Question about eCAL::Finalize/eCAL::Ok

### ISSUE THREAD

**Issue by christopherbate** [continental/ecal#271]
I have a quick question about the `eCAL::Ok` and `Finalize` functions. What's the worst that could happen if a bunch of eCAL nodes terminate without calling `Finalize` because of sigint/sigkill? (My platform is Ubuntu.) Does eCAL install any sort of signal handlers in the background? If we do need to install a signal handler, what eCAL function should it call t o ensure proper termination?

I noticed none of the samples handle signals, but after a quick search of  the code base I can't seem to find any place where they are installed by eCAL either.

**Comment by rex-schilasky** [comment]
Hi, the ```eCAL::Finalize``` function will terminate all process internal threads, close sockets, free memory and destroy all eCAL entities (Publisher, Subscriber, Clients, Services). It's only for cleaning up process resources, there is no system / background handler in general involved in the communication .. so if you forget to do a ```Finalize``` call all resources should be freed finally if your process terminates.

**Comment by christopherbate** [comment]
Thanks!
