### ISSUE TITLE
Imported protoc not working in Crosscompiling environment

### ISSUE THREAD

**Issue by pablorcum** [continental/ecal#280]
**Describe the bug**
The bug is in the main `CMakeLists.txt` lines 163-175. It is actually caused by line 168. Since protoc_imported target has been defined instead of protoc, getting a property from protoc leads to an error, because protoc is not existing when crosscompiling.

**To Reproduce**
Crosscompile eCAL.

**Expected behavior**
Move `get_target_property(is_imported protoc IMPORTED)` and the following if block into `elseif(NOT TARGET protobuf::protoc)` as shown below.

    elseif(NOT TARGET protobuf::protoc)
      add_executable(protobuf::protoc ALIAS protoc)
      set(Protobuf_PROTOC_EXECUTABLE protoc)

      get_target_property(is_imported protoc IMPORTED)
      if (NOT is_imported)
        # Disable warnings for third-party lib
        target_compile_options(protoc PRIVATE
          $<$<CXX_COMPILER_ID:MSVC>:/W0>
          $<$<NOT:$<CXX_COMPILER_ID:MSVC>>:-w>
        )
      endif()
    endif()

**Comment by hannemn** [comment]
Hello @pablorcum, in order to find protoc properly for a cross build, you have to **append** the directory of the protoc executable either to the CMAKE_FIND_ROOT_PATH or CMAKE_SYSROOT variable (depends on the CMAKE_FIND_ROOT_PATH_MODE_PROGRAM setting) in your toolchain file. The way is bit cleaner than defining the protoc target directly in a toolchain file.

**Comment by pablorcum** [comment]
Maybe, the best way of fixing this is renaming `protoc_imported` to `protoc` to use a consistent naming convention and avoid the error in line `get_target_property(is_imported protoc IMPORTED)` due to trying to get a property from a non-existing target when cross-compiling. See more details in the attached patch file.

[protocImport.txt](https://github.com/continental/ecal/files/6550000/protocImport.txt)

**Comment by hannemn** [comment]
Resolved with PR #289
