### ISSUE TITLE
Enable crosscompiling of localtime for QNX

### ISSUE THREAD

**Issue by pablorcum** [continental/ecal#282]
**Describe the bug**
The bug is located at `modules\ecal\contrib\ecaltime\localtime\CMakeLists.txt` at line 48 due to the non-existing rt library in QNX. Therefore, that line should be replaced with `$<$<AND:$<BOOL:${UNIX}>,$<NOT:$<BOOL:${APPLE}>>,$<NOT:$<BOOL:${QNXNTO}>>>:rt>`

**To Reproduce**
Crosscompile eCAL for QNX.

**Comment by pablorcum** [comment]
@hannemn This modification is the same you did in eCAL core to enable crosscompiling for QNX. I took the change from there.

**Comment by hannemn** [comment]
Hi @pablorcum, the issue will be fixed with PR #284 .

**Comment by hannemn** [comment]
Resolved with #284
