### ISSUE TITLE
I bought a mac mini last year (2018 edition) it came with python 3.8. I need python 3.8 binding

### ISSUE THREAD

**Issue by chenjo** [continental/ecal#290]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FlorianReimold** [comment]
Hi Joyce,

At the moment we only provide precompile macOS python wheels for python 3.9. So you have different options:

- Upgrade to python 3.9. I doubt that this would be difficult.
- Compile eCAL yourself. We are using homebrew to install the dependencies. Homebrew will install python 3.9, but it should be possible to use a different python version that you install with another mechanism. You can check out the [GitHub Actions File](https://github.com/continental/ecal/blob/master/.github/workflows/build-macos.yml) and the [Documentation](https://continental.github.io/ecal/development/building_ecal_from_source.html) to get help with that. 
- Switch to a different operating system. This is what I would recomment for using eCAL. eCAL for macOS is experimental and may be buggy. eCAL for Windows and Ubuntu are tested, know to work and we publish documentation on http://ecal.io.

**Comment by chenjo** [comment]
Thanks, just try to play an ecal recording in my mac to see if my conti laptop receives it in home environment and offload some laptop resources.

**Comment by FlorianReimold** [comment]
The eCAL Player does not use python. You should be able to playback a measurement by just not caring about your python version.
