### ISSUE TITLE
I purchased a Jetson Xavier NX this year, Can you provide ecal for arm64?

### ISSUE THREAD

**Issue by chenjo** [continental/ecal#291]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FlorianReimold** [comment]
Hi Joyce,

Please check out the [documentation on how to install eCAL on Ubuntu](https://continental.github.io/ecal/getting_started/setup.html#fa-ubuntu-automatically-install-ecal-from-a-ppa). When you have Ubuntu on that plattform, the PPAs have you covered. When you don't run Ubuntu on it, you will have to compile eCAL yourself.

**Comment by chenjo** [comment]
I did add-apt-repository ppa:ecal/ecal-latest. It shows Xenial instead of Bionic which is Xavier Nx's Ubuntu version

**Comment by FlorianReimold** [comment]
Not sure what you mean by that. The PPA contains binaries for:

- Ubuntu 16.04 (i386, x64, armhf, arm64)
- Ubuntu 18.04 (i386, x64, armhf, arm64)
- Ubuntu 20.04 (x64, armhf, arm64)
- Ubuntu 20.10 (x64, armhf, arm64)
- Ubuntu 21.04 (x64, armhf, arm64)

Any Ubuntu will automatically choose the correct Version.

**Comment by chenjo** [comment]
Thanks, just installed ecal
