### ISSUE TITLE
Fat source release tarball

### ISSUE THREAD

**Issue by rhd** [continental/ecal#335]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
If you could provide a fat source tarball with the `git submodules` ready to go it would be great

**Describe alternatives you've considered**
Manually doing it

**Additional context**
Some situations it's easier to just grab a tarball and know it's got everything it needs already included.

**Comment by FlorianReimold** [comment]
I have created a GH Actions run that uploads fat-source taballs. For Windows you still need to install Qt and download Npcap and PcapPlusPlus though.

The fat-source tarball has a patched git-get-revision-information.cmake, as usually the eCAL Version is determined by the git tag and I didn't want to include a .git directory in the source tarball.

**Comment by rhd** [comment]
This is great! Thank you :+1:
