### ISSUE TITLE
Update ecal iceoryx layer with iceoryx v1.0.1 version.

### ISSUE THREAD

**Issue by ZhenshengLee** [continental/ecal#352]
**Describe the bug**

Recently iceoryx released its v1.0.1 version, I downloaded recent ecal fat source and try to compile the code with iceoryx_layer. And failed due to  version mismatch.

**To Reproduce**

With recent ecal release fat source tree, compile with options below.

```sh
cmake .. -DCMAKE_BUILD_TYPE=Release -DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF -DECAL_THIRDPARTY_BUILD_CURL=OFF -DECAL_THIRDPARTY_BUILD_HDF5=OFF -DECAL_LAYER_ICEORYX=ON

make -j10
```

**Expected behavior**

Compile the code with no error

**Screenshots**

![image](https://user-images.githubusercontent.com/17764118/126601701-70c70b16-a2a5-4a4f-baae-d11ee6c207c3.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Version: 20.04
 - iceoryx: release1.0

**Additional context**

It is a simple mismatch of software version.

I wonder if ecal team will keep maintaining with this layer.

**Comment by FlorianReimold** [comment]
eCAL 5.8 is not compatible with iceoryx 1.0. Please try the master branch! Iceoryx had a major API break some time ago, so it doesn't work any more in eCAL 5.8

**Comment by ZhenshengLee** [comment]
> eCAL 5.8 is not compatible with iceoryx 1.0. Please try the master branch! Iceoryx had a major API break some time ago, so it doesn't work any more in eCAL 5.8

Thanks for your reply!
