### ISSUE TITLE
Clean up plugin loading strategy

### ISSUE THREAD

**Issue by Kerstin-Keller** [continental/ecal#363]
Unify loading strategy of eCAL Time / Monitor Plugins

Plugins should be loaded in different location

Time:
- in folder relative to ecal.dll 
  - Unix: ./ecal/plugins/time
  - Windows: ./ecaltime_plugins/
- all folders in `$ECAL_TIME_PLUGIN_DIR`

Monitor: 
- in folder relative to mon(.exe) 
  - Unix: ???
  - Windows: ./ecalmon_plugins/
- all folders in `$ECAL_MON_PLUGIN_DIR`

Some logic will be necessary to determin path of `ecal.dll|.so`.

**Comment by hannemn** [comment]
Added with #379
