### ISSUE TITLE
Move Qt Related files into a separate folder

### ISSUE THREAD

**Issue by BriFuture** [continental/ecal#364]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when developing qt widgets application, my qt version (5.12.9) conflicts with the qt from ecal (5.15.2).

**Describe the solution you'd like**
I want to develop with ecal and my qt version without modifying PATH variables every time I run my qt application.

What about moving all qt related files into a separate folder like this:
![image](https://user-images.githubusercontent.com/7582298/129432655-3a447257-022a-4669-9abb-ed98a439f6e1.png)

Current time I have to do it mannualy but I wish there is an option during install stage.

**Comment by Kerstin-Keller** [comment]
Hi @BriFuture,
we're already internally having a discussion, how it's not a good practice for programs to set the `PATH` environment variable, because it can lead to unintended sideeffects, like the one you describe.
One idea can be like you described, have only `ecal_core.dll` inside the `PATH`, but not the Tools which do need additional dlls.

Thanks for opening this issue, we will keep you posted.

**Comment by FlorianReimold** [comment]
Hi BriFuture, I guess the load preference of qt dlls is something every Qt Developer will stumble upon at some point. So before we change eCAL, I think we should look at best practices for Qt on Windows.

Windows will load dlls from:
- The directory the executable is located in
- The PATH (if the dll is not found in the directory)

Windows does not define a "standard" Qt Version, like most Linux distributions. Additionally, the dlls from all Qt Versions have the same name, so you cannot distinguish between them. Each application however needs the Version of Qt that is has been linked against.

**There cannot be a globally defined Qt Installation on Windows that will work for all applications**

Thus, the best practice is:

**Each Application has to ship its own Qt dlls next to the .exe files that need them.**

Assuming to have proper dlls in PATH will cause troubles. You are already experiencing that. Sure, you can try to keep your path clean of all Qt dlls, but there will always be another application that has to add binaries to the PATH and pollutes it with Qt dlls again. Qt is used by a lot of applications.

So my tip is: Even when developing, do it properly, follow the best practice and copy the qt dlls next to your exe. There is even a qt tool that does that for you (windeployqt.exe). You can add that as post-build step in basically any build system. Life is easier this way 👍

**Comment by BriFuture** [comment]
Thank you for the instructions. 
Your tip is useful but I have another opnion : we can just do like what QtCreator does (which replies on certain Qt Versions). QtCreator is based on Qt5.15.2 on my computer but I'm developing an qt application based on Qt5.12, 

After I installed Qt with QtCreator, it creates a folder named Tools under  root directory and put all the Qt libraries into that folder like this:

![image](https://user-images.githubusercontent.com/7582298/129534703-872b0d90-2f05-4a00-a851-06cb56c10f98.png)

**Comment by FlorianReimold** [comment]
Yes, QtCreator does not add itself to the PATH. But if you want your application to be accessible from anywhere, you have to add the directory to the PATH. And we do want that with eCAL.

Your own application cannot cannot rely on all applications not modifying the PATH. You so you will have to ship a whole set of dlls along with your exe anyways. And once you ship all required Qt dlls, you don't have to care about the PATH any more.

**Comment by BriFuture** [comment]
Thanks, I will follow your instructions.
