### ISSUE TITLE
Service client `Call` and `CallAsync` APIs do not have a timeout argument

### ISSUE THREAD

**Issue by bsirang** [continental/ecal#372]
**Describe the bug**
The APIs in `ecal_client.h` for `CServiceClient::Call` and `CServiceClient::CallAsync` do not have a timeout option. It doesn't appear the user has any way of bounding the time that the operation takes. This makes it more challenging for application code to be robust against missing or unresponsive services.

**To Reproduce**
1. Initiate a `Call` to a very long running service handler

**Expected behavior**
The client call fails after a user-specified timeout and signals the timeout to the application.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Additional context**

**Comment by rex-schilasky** [comment]
@bsirang Hi, let us check what we can do here. We are working on a few other issues we will hopefully close soon. I fully agree that a timeout would be a nice option here. The services are handled by underlaying ASIO sockets and I remember that there was no option for timeout offered by the API. But let's check again.

**Comment by bsirang** [comment]
Hi @rex-schilasky I actually have a fair bit of ASIO experience and I have implemented timeouts as well, so I'm happy to provide guidance.

The pattern I've used before was to kick off a timer with the IO request.

If the timer expires first, then it aborts the pending IO operation, and then the IO callback will get an "operation aborted" error, which you can treat as a timeout condition.

If the IO operation completes first, you can cancel the timer. You would have to couple a timer operation with each IO operation.

**Comment by bsirang** [comment]
When I say "It aborts the pending IO operation", I mean invoking `cancel()` method such as from: https://think-async.com/Asio/asio-1.18.2/doc/asio/reference/basic_stream_socket/cancel.html

**Comment by bsirang** [comment]
Oh, and I should mention that the timer and the socket operation should happen on the same event loop (same io_context) so that the timer expiration and the IO operation can't truly simultaneously complete. One always comes first. This avoids potential race conditions.

**Comment by rex-schilasky** [comment]
Hi @bsirang, I will start to work on that issue now. It will be part of an eCAL service / client API redesign. See PR #427. I will change the signature of the blocking service call API first and add a timeout event to the new EvenCallback logic. Let us discuss here how to implement the timeout logic the right way.

**Comment by bsirang** [comment]
Hi @rex-schilasky I appreciate the update! I'm happy to look at any code you point me toward and/or discuss implementation details. Cheers.

**Comment by rex-schilasky** [comment]
@bsirang I started with a redesign of the eCAL server/client API now. There is a new `timeout_` parameter, can you please check [ecal_client.h](https://github.com/continental/ecal/blob/d086f8c3adc73f7d9515cf1a06051a7630fb53a6/ecal/core/include/ecal/ecal_client.h) ? Does that fit for you so far ?
Additional there is a new event callback logic, that can be used to get informed for connect and disconnect but for timeout events as well.
Next step is to finalize the API in all variants (C++, C, Python), after that it would be great if you could give some support how to implement the timeout logic the right way. Best, ReX

**Comment by bsirang** [comment]
The API with `timeout_` looks reasonable to me. I did notice you included a default value `int timeout_ = -1` in the `Call` method but not `CallAsync` of `CServiceClientImpl`. I wasn't sure if that was intentional or not.

Yes let me know when/how you want to discuss the implementation.

**Comment by rex-schilasky** [comment]
> The API with `timeout_` looks reasonable to me. I did notice you included a default value `int timeout_ = -1` in the `Call` method but not `CallAsync` of `CServiceClientImpl`. I wasn't sure if that was intentional or not.
> 
It wasn't intentional, thank you - corrected now. Do you have any kind of simple ASIO based client / server sample supporting timeout client calls ?

**Comment by bsirang** [comment]
I did attempt to wrap eCAL's service client with timeout functionality. It hasn't been rigorously tested: https://github.com/agtonomy/trellis/blob/master/trellis/core/service_client.hpp

The timer that's created on line 45 is asio-based. The eCAL service call response handler uses asio::post to invoke the user callback on the event loop.

This code demonstrates the high-level strategy where the timeout timer callback retains a handle to the client, and the client response callback retains a handle to the timer. Whichever one fires first aborts the other and calls back to the user. Note the comment on line 48 because there wasn't an API to abort a pending async call.

**Comment by rex-schilasky** [comment]
Thank you, will check this now.

**Comment by Marco-MFC** [comment]
I'm using with success this feature, I hope it will be incorporated in the next official release.

**Comment by rex-schilasky** [comment]
> I'm using with success this feature, I hope it will be incorporated in the next official release.

Glad to hear that. This fix will be part of eCAL 5.10.

**Comment by rex-schilasky** [comment]
Will be part of the future 5.10 release.
