### ISSUE TITLE
Arduino Pro Support

### ISSUE THREAD

**Issue by ahoarau** [continental/ecal#377]
Hello all,
Very nice library, seems to be a good ros2 alternative.
Do you think possible to port the code for the arduino pros (Portenta H7 core) ?
Best,

**Comment by FlorianReimold** [comment]
Hi Ahoarau,

I haven't developed for Arduions for quite some time, but the last time I did it, Arduinos were just micro controllers without any OS (Arduino Uno, Mini, Micro etc.). Is there any way to get some kind of "standard" operating system on that specific Arduino? Like Linux, Yocto, BSD or something like that? If not, then there is probably no way to get eCAL running on the plattform.
If you need an embedded / embeddable plattform I suggest you use a Raspberry PI for that. If you run Ubuntu on that, you don't even have to compile eCAL yourself; you could simply `apt install ecal` from our PPA.

Regards
Florian
