### ISSUE TITLE
When ECAL_THIRDPARTY_BUILD_FINEFTP=OFF binaries aren't linked with libfineftp-server.so

### ISSUE THREAD

**Issue by yurivict** [continental/ecal#381]
**Describe the bug**
I have externally installed fineftp-server. cmake is given ```ECAL_THIRDPARTY_BUILD_FINEFTP=OFF```. Resulting binaries aren't linked with ```libfineftp-server.so```.

Version: 5.10.0-nightly
OS: FreeBSD 13

**Comment by FlorianReimold** [comment]
Hi Yurivict, 

While this actually is a fineftp thing, since fineFTP 1.1.0 both dynamic linkage and static linkage should work properly. Do you have a possibility to try again?

**Comment by FlorianReimold** [comment]
Closed due to inactivity
