### ISSUE TITLE
[ecalPlayer] Possibility to save timestamp labels on a custom/configurable location

### ISSUE THREAD

**Issue by suvigy** [continental/ecal#384]
**Is your feature request related to a problem? Please describe.**
In our case the recordings are available in a read-only mode, we'd like to manually select certain timestamp ranges. For that adding labels seem to be really useful feature to mark start and end of range of interest. When trying to save them we get an error "Unable to save Labels to disk"

**Describe the solution you'd like**
"Save Labels As..." in Files menu would be a good solution, I guess

**Describe alternatives you've considered**
Configuring a custom labels path would be also a solution

**Comment by FlorianReimold** [comment]
Seems like a good idea!
