### ISSUE TITLE
support for other type of msg publishing

### ISSUE THREAD

**Issue by EVYang1992** [continental/ecal#393]
I am confused if ecal can publish other message type except string and protobuf, for example i just want to publish a simple int value or a C++ struct type value?

Supporting C++ struct type value will be highly appreciated.

If this can be simply solved by a known(already implemented in version v5.9) method, please let me know.

**Comment by FlorianReimold** [comment]
Hi,
A C++ Struct is just raw memory. [Iff](https://en.wikipedia.org/wiki/If_and_only_if) your struct ist a [POD](https://stackoverflow.com/questions/146452/what-are-pod-types-in-c) struct and does not contain any pointer types, you can send the raw memory (via Pointer & length). You can use the string publisher for that, or a raw CPublisher. But be aware that the binary layout of your struct is Architecture, OS and Compiler specific. So if you send that data to another machine, everything may fail. So doing this is not recommended, you really should use a proper serialization like protobuf.

Regards
Florian

**Comment by rex-schilasky** [comment]
Here you can find a sample how to send a single `long long` for example [samples/cpp/counter/counter_snd](https://github.com/continental/ecal/blob/master/samples/cpp/counter/counter_snd/src/counter_snd.cpp). As @FlorianReimold mentioned you can send any kind of memory using [`eCAL::CPublisher::Send`](https://continental.github.io/ecal/_api/classeCAL_1_1CPublisher.html#_CPPv4NK4eCAL10CPublisher4SendEPCKv6size_tx), but you have to know that sending raw memory to another process may cause trouble.

**Comment by EVYang1992** [comment]
@FlorianReimold @rex-schilasky Very appreciate for the quick reply. One further question: is the CPublisher also implemented in python api if i use cstruct such package?

**Comment by rex-schilasky** [comment]
In python you can use the [`ecal_core.publisher`](https://github.com/continental/ecal/blob/80a41b310f43cc234a7200bbb4ff00597eeed3a2/lang/python/core/ecal/core/core.py#L552), see [`samples/python/latency_snd.py`](https://github.com/continental/ecal/blob/80a41b310f43cc234a7200bbb4ff00597eeed3a2/samples/python/latency_snd/latency_snd.py#L48) how to use it.

```
# import ecal core
import ecal.core.core as ecal_core

# initialize eCAL API
ecal_core.initialize([], "simple python publisher")

pub = ecal_core.publisher('pub42')

# create message of 2048 byte
msg = b'42' * 1024

# send message
pub.send(msg)
```

**Comment by EVYang1992** [comment]
@rex-schilasky Awesome, thanks again for the help and great work in regarding to eCAL project.
