### ISSUE TITLE
Proto messages with default values aren't transmitted by `eCAL::protobuf::CPublisher<T>`

### ISSUE THREAD

**Issue by bsirang** [continental/ecal#397]
**Describe the bug**
A default proto message, which has default values for all fields, doesn't seem to be sent over the wire.

**To Reproduce**
1. Create a `eCAL::protobuf::CPublisher<T>`
2. Default construct the proto message `T`
3. Call the `Send()` method with the default proto message
4. Observe subscribers do not receive anything

**Expected behavior**
The subscribers would receive the message. I understand protobufs do not serialize the default values over the wire thus the serialized proto payload would be zero-length in this case. However, in these cases, I'm expecting the subscriber to still receive the message.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by bsirang** [comment]
I believe this check may be where this behavior is stemming from: https://github.com/continental/ecal/blob/962c8340720fe51c4e1f8aa0e8ed3d15075e881e/ecal/core/src/pubsub/ecal_publisher.cpp#L269

**Comment by rex-schilasky** [comment]
This is a known behavior. In the case of a zero-length message the underlaying API is not initiating the publication. In this specific context (zero length default google message). Thank you for the feedback we need to check how we can fix that.

**Comment by rex-schilasky** [comment]
@FlorianReimold can you please apply this fix to the next 3.9.x release ?

**Comment by rex-schilasky** [comment]
@bsirang fix is available on master, will be part of next release.
