### ISSUE TITLE
CMake developer warning (qt_windeployqt_cmake_path.cmake on Linux)

### ISSUE THREAD

**Issue by mt1871** [continental/ecal#416]
I've installed eCAL 5.9.1 on Ubuntu 20.04.3 LTS via PPA. Our application is built using CMake 3.21.4 and links against eCAL. During CMake's configuration phase of our application, the following warning is printed:
```
CMake Warning (dev) at /usr/lib/cmake/CMakeFunctions-0.4.1/qt/qt_windeployqt.cmake:20 (set):
  Cannot set "qt_windeployqt_cmake_path": current scope has no parent.
Call Stack (most recent call first):
  /usr/lib/cmake/CMakeFunctions-0.4.1/cmake_functions.cmake:24 (include)
  /usr/lib/cmake/CMakeFunctions-0.4.1/CMakeFunctionsConfig.cmake:38 (include)
  /usr/lib/x86_64-linux-gnu/cmake/eCAL/eCALConfig.cmake:81 (find_package)
  CMakeLists.txt:41 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Here, line 41 of CMakeLists.txt reads as follows:
```
find_package(eCAL REQUIRED)
```

**Comment by FlorianReimold** [comment]
Hi Thom,

Thanks for pointing that out. Even though I agree that the warning is annoying, you can safely ignore it. That file is only used on windows for copying Qt .dll files. It shouldn't exist in the Linux Setup, but it doesn't break anything either. It just generates that annoying warning.

Regards
Florian

**Comment by mt1871** [comment]
> Hi Thom,
> 
> Thanks for pointing that out. Even though I agree that the warning is annoying, you can safely ignore it. That file is only used on windows for copying Qt .dll files. It shouldn't exist in the Linux Setup, but it doesn't break anything either. It just generates that annoying warning.
> 
> Regards Florian

Hi Florian,

Thank you for the quick reply. I will ignore the warning for now just as you suggested, but it would be great if this could be fixed in any of the upcoming eCAL releases. Otherwise it will become difficult to spot actual errors if the CMake output remains this communicative :)

Many thanks,
Markus
