### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by JeremyBYU** [continental/ecal#42]
I was wondering if ECAL has ever been compiled and tested on Android.  I did a search and found some info on android https://github.com/continental/ecal/search?q=android&unscoped_q=android. However I'm not sure if that really indicates support. I was wondering if it would be possible to make an android app that can subscribe to topics and services being published on a local network. Similar to how ROS is supported on Android.

If it's not currently possible, I was wondering if it was something on the roadmap for ECAL.

Thanks!

**Comment by FlorianReimold** [comment]
At the moment, we only support Windows and Linux. But eCAL also runs on MacOS, although we don't really support it. You could try compiling it for Android. Android is just a Linux, so I assume it shouldn't require that much modifications.

**Comment by JeremyBYU** [comment]
Thanks for the response! If I have time I might try to compile for android. I was just worried if the networking code would have to be changed.
