### ISSUE TITLE
32bit SDK / Python builds on Windows

### ISSUE THREAD

**Issue by Kerstin-Keller** [continental/ecal#421]
We always get requests for artifacts of 32bit builds of the SDK / Python wheels.
Let's add another action, and build them. (No tooling, for sure)

**Comment by FlorianReimold** [comment]
Tasks that need to be done to support this:
- GH Action building 32bit binaries & python wheels
  - Optional: Cherry-pick to support branches, if we want to support this in 5.9 / 5.8
- Documentation upgrade (Support in [download table](https://github.com/continental/ecal/blob/master/doc/extensions/resource/download_table.html.em))
  - Optional: supported in support branches, this must also be cherry-picked
