### ISSUE TITLE
Linux build instructions don't work (missing dependencies)

### ISSUE THREAD

**Issue by frostybeard** [continental/ecal#43]
Hi, The LInux build instructions are missing mention of simpleini. 
Could you add something there in the documentation? I can find a simpleini project in GitHub, but it is not the only one. Document what to put into the empty simpleini folder, for example.

Thanks

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find simpleini (missing: simpleini_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/Findsimpleini.cmake:18 (find_package_handle_standard_args)
  CMakeLists.txt:159 (_find_package)
  ecal/core/src/CMakeLists.txt:24 (find_package)

**Comment by Kerstin-Keller** [comment]
Hi @frostybeard.

have you checked out the repository including the submodules? `git clone --recurse-submodules https://github.com/continental/ecal.git`. Everything should be included, then.

**Comment by FlorianReimold** [comment]
Or if you have already checked out the repository call 
```
git submodule init
git submodule update
```

**Comment by frostybeard** [comment]
Thanks. That worked.
