### ISSUE TITLE
eCAL Mon Plugin for plotting data

### ISSUE THREAD

**Issue by FlorianReimold** [continental/ecal#434]
**Is your feature request related to a problem? Please describe.**
This issue is about adding a graphical plotting monitor plugin, that shall be able to visualize simple numeric data in a graph.

![signal plotting](https://user-images.githubusercontent.com/11774314/144589221-4075f90e-48df-4ddf-b3a6-5a24ee5fe393.png)

**Comment by ishansheth** [comment]
Hi, 
I am using eCAL and I would like to contribute to the project. Is there any contribution guide for the project and is it possible to work on this issue or any other more important issue?
Best regards

**Comment by FlorianReimold** [comment]
Hi Ishan,

Happy to hear you want to contribute! 🙌
In the repository root you can find the [CONTRIBUTING.md](https://github.com/continental/ecal/blob/master/CONTRIBUTING.md)

So in general, it works this way:
- You detect some thing that you are missing in eCAL. This can be a bug or a feature. Choose something that you would benefit from yourself. If it is a bigger thing you may want to tell us beforehand, as maybe we already have a solution for that use-case. If you want to work on an existing ticket give us a note, so we don't end up with two developers doing the same thing at the end.
- You fork eCAL, implement and create a PR
- We review and merge the code. Please don't mind if it takes some time (especially for bigger changes), as we have internal processes to follow.

This exact ticket (the monitor plotting plugin) is already being worked on and will be pushed at some point. The code has to go through our internal audits though, wich takes some time. So you can lean back and wait for things to unfold from our side.

Regards
Florian

**Comment by ishansheth** [comment]
Ok thanks. Is it possible to work or the issues already created in the list and solve one of them?
