### ISSUE TITLE
Add generic description field to CSubscriber/CPublisher

### ISSUE THREAD

**Issue by brakmic-aleksandar** [continental/ecal#436]
**Is your feature request related to a problem? Please describe.**
Currently CSubscriber/CPublisher classes have topic_desc_ argument in their constructors, but it is used mainly for their type description, it would be nice if we had generic description field as well which could be used to have some metadata related to specific subs/pubs or just to add plain text descriptions for them.

**Describe the solution you'd like**
Rename topic_desc_ cosntructor parameters to type_desc_ and add topic_desc_ optional string argument to them, this way it shouldn't break API.

**Comment by brakmic-aleksandar** [comment]
Additional info:
This feature is needed by rmw_ecal to implement [get_topic_endpoint_info functions](https://docs.ros2.org/foxy/api/rmw/get__topic__endpoint__info_8h.html) which provide node name/namespace for specific pub/sub (which is required by ros tools such as rosbag), the best way to do this would be to specify additional field in monitoring layer which should contain info needed for those functions, to make this feature not specific to rmw_ecal i propose we name new monitoring field either generic_desc or endpoint_desc and make it a string field, so that it can be applied to different use cases.

**Comment by FlorianReimold** [comment]
So we would basically extend the topic info
https://github.com/continental/ecal/blob/master/ecal/pb/src/ecal/pb/topic.proto#L45

which is used in the big monitoring information struct:
https://github.com/continental/ecal/blob/master/ecal/pb/src/ecal/pb/monitoring.proto#L45

and expose setting this user-defined field to anything.
