### ISSUE TITLE
eCAL on NVidia Jetson TX2

### ISSUE THREAD

**Issue by jldk20** [continental/ecal#44]
Hi, is there a way to run eCAL on the NVidia Jetson TX2 Embedded device?

**Comment by FlorianReimold** [comment]
Hi jldk20,
As we only provide precompiled binaries for Linux AMD64, you have to compile eCAL yourself. But eCAL is known to work on ARM 64 (we use that internally).
If you have a somehow recent Linux on your device there might be a good chance that eCAL will work. If the CPU is somehow capable of compiling, I suggest you do not look into crosscompiling but compile natively on your platform for a first test.

Here are my recommended CMake options (basically turning everything off but the samples):
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DHAS_HDF5=OFF -DHAS_QT5=OFF -DBUILD_DOCS=OFF -DBUILD_APPS=OFF -DBUILD_SAMPLES=ON
```

If you  can get your hand on precompiled protobuf binaries it may be worth to also turn off building thirdparty protobuf as that takes a lot of time.

then set your routes any try the ecal_sample_person_snd and ecal_sample_person_rec samples!

Good luck! :)

**Comment by jldk20** [comment]
Hi Florian,
thank you very much, everything is working now after compiling from scratch!

**Comment by fei4xu** [comment]
Any plan to release a **pre-built** version .deb for arm64, for example, Jetson platform?

**Comment by FlorianReimold** [comment]
Hi fei4xu,

We already provide precompiled arm64 builds for Ubuntu 16.04, 18.04, 20.04 and 20.10 (architectures i386, amd64, armhf, arm64). You can get them from the PPA:
https://continental.github.io/ecal/getting_started/setup.html#fa-ubuntu-automatically-install-ecal-from-a-ppa

If you are not using Ubuntu, those builds will probably not fit your plattform and you have to compile eCAL yourself:
https://continental.github.io/ecal/development/building_ecal_from_source.html

**Comment by fei4xu** [comment]
thanks for mentioning it, I will give it a try.

**Comment by fei4xu** [comment]
I tried and it worked, I successfully installed ecal on Jetson Nano.

One minor issue though: the python binding is not installed along with the ppa installation.
I'm not sure the amd64 .whl file can work on the arm64 platform.
