### ISSUE TITLE
Using source built library - cannot find CMakeFunctions lib

### ISSUE THREAD

**Issue by SimonTigo** [continental/ecal#440]
**Describe the bug**
Linux, Ubuntu 20

I have built eCAL from source (9.5.2 tag, but problem is also on current code 10.0.0) and then installed it using cpack. Using cmake, I call the package created by providing the path to it using 
`find_package(eCAL 5.9.2 EXACT REQUIRED PATHS "path/to/library")`

but when I build my project, I get folloswing error:

```
  project has asked CMake to find a package configuration file provided by
  "CMakeFunctions", but CMake did not find one.

  Could not find a package configuration file provided by "CMakeFunctions"
  with any of the following names:

    CMakeFunctionsConfig.cmake
    cmakefunctions-config.cmake

  Add the installation prefix of "CMakeFunctions" to CMAKE_PREFIX_PATH or set
  "CMakeFunctions_DIR" to a directory containing one of the above files.  If
  "CMakeFunctions" provides a separate development package or SDK, be sure it
  has been installed.
```
 even though the CMakeFunctions-0.4.1 is located in lib/cmake.

I fixed the issue by adding `
set(CMakeFunctions_DIR "${PACKAGE_PREFIX_DIR}/lib/cmake/CMakeFunctions-0.4.1")`

right above the `find_package(CMakeFunctions REQUIRED)` in the eCALConfig.cmake

Maybe this is solved if eCAL is installed via deb file using dpkg, but doesn"t hurt adding the CMakeFunctions_DIR so the library can be accessed statically.

**Comment by Kerstin-Keller** [comment]
Hi @SimonTigo,

usually, the user is responsible for telling CMake that it needs to search for libraries/modules in non-standard paths.
The generic way to do this, is to set this on a CMake invocation:

```
mkdir _build && cmake _build
cmake .. -DCMAKE_PREFIX_PATH="path/to/uncommon/folder"
```

With a very recent CMake version (>3.20), you can also create a `CMake(User)Presets.json` file, where you put this information.

I would strongly recommend against doing 
```
find_package(eCAL 5.9.2 EXACT REQUIRED PATHS "path/to/library")
```
as this effectively will work only on your machine. The `CMAKE_PREFIX_PATH` approach is a lot more generic.
If you set it, `CMakeFunctions` will also be found.
