### ISSUE TITLE
pub data loss when pub.send continously

### ISSUE THREAD

**Issue by LevineYang** [continental/ecal#441]
**Describe the bug**
here i'm doing test on the pub/sub of ecal, I found that when I do publisher.Send more than twice without delay, the subscriber cannot get most of the data. But when I do even "usleep(1)" between them, the sub process can be done perfectly. I want to know why this happened and is there a solution for it?

**To Reproduce** The sample pub code I used is like following, if the receive part is needed, I could paste later:

#include <ecal/ecal.h>
#include <ecal/msg/string/publisher.h>
#include "unistd.h"
#include <thread>
#include <iostream>
int main(int argc, char** argv)
{
  eCAL::Initialize(argc, argv, "Hello World Publisher");
  eCAL::string::CPublisher<std::string> publisher("front_cam");
  std::cout << publisher.Send("89") << std::endl;
  //usleep(1);
  std::cout <<  publisher.Send("98") << std::endl;
  //usleep(1);
  while (eCAL::Ok())
  {
    	publisher.Send("11");
    	publisher.Send("01");
    	std::this_thread::sleep_for(std::chrono::milliseconds(50));
  }
  eCAL::Finalize();
}

**Expected behavior**
I hope to know the reason, if better, to solve this problem.

**Comment by rex-schilasky** [comment]
Hi, the publish / subscribe connection over shared memory is loosely coupled. That means the publisher is not synchronized with the processing of the message content by the subscribers. So if you send faster than your subscriber are able to process you will loose samples. This is a design decision for maximum performance.
There is a configuration setting to establish a handshake with timeout if needed.

**Comment by LevineYang** [comment]
> 
Hi, thank you for the reply! According to your suggestion, I try to find "timeout" related settings in ecal.init file, there are "registration_timeout", "memfile_ack_timeout" and "timeout", but no one seems to work.
Can you please give some more hints for where to configure the setting for test?

**Comment by rex-schilasky** [comment]
Hi, you are welcome. It's the 'memfile_ack_timeout'. Depending from your subscription processing speed, set it to a maximum value in milliseconds to force the publisher to wait for an acknowledgment from the connected subscriber.
You can set it to a 100 ms for a first test.
In general - often it makes not so much sense to fire 2 or more values with single publications without any delay. You could aggregate all values you need to transfer in on shot into a memory array (vector) or send it as an serialized protobuf message. This is easier to handle for the receiver side.

**Comment by LevineYang** [comment]
> 

Thank you for the suggestion! Solution verified, issue close.
