### ISSUE TITLE
Dynamic Service Client

### ISSUE THREAD

**Issue by bsirang** [continental/ecal#456]
**Is your feature request related to a problem? Please describe.**
I'd like to develop a generic utility to issue service calls to arbitrary service servers since it is a useful tool for testing and development.

I did something similar with publishing by using this API `eCAL::Util::GetDescription(topic);` to get the protobuf description during runtime so I can create a dynamic publisher.

**Describe the solution you'd like**
Ideally I'd like some APIs available to be able to query the service definitions at runtime to be able to call methods dynamically.

**Additional context**
I'm trying to write a command line utility that would take a JSON string for the request message and a method name to then convert into the request message and call the service with.

**Comment by rex-schilasky** [comment]
Hi @bsirang,

that sounds like a nice generic idea. Currently the eCAL registration layer is transporting the service descriptor only, without the descriptors for request and response types. You check this by running the `monitoring_reg` sample.

![image](https://user-images.githubusercontent.com/49162693/150140305-ad254345-4795-4513-9b79-c6160a88276b.png)

So before we can implement this feature we need to add the missing information here I think. What do you mean ?

Best, ReX

**Comment by bsirang** [comment]
Hi @rex-schilasky yes that sounds correct. I think it would be a good idea to include the missing information there first, and then that would enable what I'm describing to be possible.

**Comment by rex-schilasky** [comment]
Hi @bsirang, I created a primitive prototype now that is extracting the type information out of a service description. You can check the demo repository [here](https://github.com/rex-schilasky/ecal_service_dyntypes).

The output looks like this

![ecal_service_dyntypes_log](https://user-images.githubusercontent.com/49162693/161216225-9c4c9639-2fbe-4f31-b3e2-381f719e1d5f.png)

So the service method types are _human readable_ protocol buffer definition. Does that fit to your needs or do you needs protocol buffer descriptors like we do it for topic type descriptors ?

Next step would be to add these information to the monitoring layer and finally to have a `eCAL::Util` function retrieving that information. Currently I have no idea how to signature of such a function could look like. Maybe you have an idea :-). We would need the service name, the method name and get the request and response type descriptors ?

**Comment by Kerstin-Keller** [comment]
@rex-schilasky wouldn't it be more in line with the rest of our information if they were actual descriptors instead of the human readable buffer definitions?
I guess it would be helpful if we would want to reflect on these types?

 E.g. I think it would be really, really great if we could monitor service calls, I know it's technically not possible (because yeah it's a TCP 1:1 connection), but maybe clients could send request infos and the servers the response info also on the monitoring layer.

Let me know if you'd like me to step in on the magic :smile:

**Comment by bsirang** [comment]
Thanks for your efforts on this @rex-schilasky! Human readable sounds nice for debugging, but I agree with @Kerstin-Keller and think it makes for sense for them to be in the same binary format as the pub/sub message descriptors.

My use case would be to generate a request message at runtime based on the descriptor, so I'd be using proto APIs to do it. Being able to query the request and response descriptors of an rpc call at runtime for use with proto APIs would be great.

**Comment by bsirang** [comment]
This is great! For my needs, what I would want to do is use protobuf's `google::protobuf::util::JsonStringToMessage` to convert a JSON string into a message. In order to use `JsonStringToMessage` I would first need to create an instance of a `google::protobuf::Message`. For pub/sub, I used `eCAL::protobuf::CProtoDynDecoder`, which has a `GetProtoMessageFromDescriptorSet` method. I assume something similar can be done in this case.

**Comment by rex-schilasky** [comment]
@bsirang I implemented a c++ [ping client sample](https://github.com/continental/ecal/blob/hotfix/dynamic_service_client/samples/cpp/services/ping_client_dyn/src/ping_client_dyn.cpp). It's working quite nice.

The ping server is communicating with the dynamic client perfectly:
![image](https://user-images.githubusercontent.com/49162693/163342003-f3070089-d2cd-4a44-b40a-ba7b6e098228.png)

**Comment by bsirang** [comment]
@rex-schilasky awesome! I just took a peak at your implementation of `GetSerialzedMessageFromJSON`. It makes sense to me and matches my use case. Looking forward to trying it myself.

**Comment by rex-schilasky** [comment]
I will split that function into smaller ones to improve performance like @Kerstin-Keller recommended in the PR.

**Comment by rex-schilasky** [comment]
@bsirang the implementation is done so far, please recheck the [ping client dynamic sample](https://github.com/continental/ecal/tree/hotfix/dynamic_service_client/samples/cpp/services/ping_client_dyn/src). Maybe the two conversion function from JSON to proto and back will get part of the eCAL API any day. For now I would keep it as it is.

**Comment by bsirang** [comment]
Just reviewed it again. Looks good to me. Do you have an approximate timeline for when this will be in a release?

**Comment by FlorianReimold** [comment]
The timeline can be seen here:
https://github.com/continental/ecal/milestone/1

So the release will be on 2022-05-09.
