### ISSUE TITLE
Failure by "create_python_egg "

### ISSUE THREAD

**Issue by im-Kitsch** [continental/ecal#46]
Hello,

I use a VM to install, and follow the instructions to build the software but fails by the step 
**Compile eCAL**
     4.Create and install the eCAL python egg
          `cmake --build . --target create_python_egg --config Release`

when I run `cmake --build . --target create_python_egg --config Release`， it shows "No rule to make target"create_python_egg", Stop ".

What is the reason?

Info: 
Ubuntu 18.04.

Thanks

**Comment by im-Kitsch** [comment]
ok, I see, parameter "BUILD_PY_BINDING" in CMakeList.txt should be changed to ON before compile.

Any way, I recommend you to add a small comment by the Compile step for generate PYTHON binding.

**Comment by rex-schilasky** [comment]
We will mention this explicitly in the upcoming release 5.5.5.
