### ISSUE TITLE
Compile eCAL Issue when enabled the BUILD_PY_BINDING option on Ubuntu 16.04,python 2.7

### ISSUE THREAD

**Issue by long131ss** [continental/ecal#460]
**To Reproduce**
1. enabled the BUILD_PY_BINDING CMake option
2.cmake .. -DCMAKE_BUILD_TYPE=Release -DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF -DECAL_THIRDPARTY_BUILD_CURL=OFF -DECAL_THIRDPARTY_BUILD_HDF5=OFF 
3.make -j4

**Expected behavior**
There should be compiled with no errors.

**Screenshots**
![Selection_164](https://user-images.githubusercontent.com/7857437/149094749-3c450fa3-ebd5-467e-aab8-aab972404cb5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04
 - Python 2.7

**Comment by rex-schilasky** [comment]
Hi, unfortunately we do not support the python 2.x series anymore. Do you have a chance to use python 3 ?

**Comment by FlorianReimold** [comment]
Just to mention this: We do provide ready-to-use builds of eCAL and the python binding for Ubuntu 16.04 from the PPA:

https://continental.github.io/ecal/getting_started/setup.html#fa-ubuntu-automatically-install-ecal-from-a-ppa

```bash
sudo apt install ecal
sudo apt install python3-ecal5
```

Using that PPA however will force you to use the Protobuf 3.1 version that we randomly added as dependency (Protobuf 2 as supported by Ubuntu 16 is not sufficient, so there was no other choice)

**Comment by long131ss** [comment]
> 
Thank you, FlorianReimold. It seems the easiest way. I will try it. @FlorianReimold

**Comment by FlorianReimold** [comment]
Hm, I tried it in a fresh Ubuntu 16 VM and it does work for me. It's the x86_64 version, though. You appear to be on an ARM system and I don't really have a way of testing that.

```bash
sudo add-apt-repository ppa:ecal/ecal-latest
sudo apt-get update
sudo apt install ecal python3-ecal5
```

![ecal_python](https://user-images.githubusercontent.com/11774314/149921127-9f05c73a-4180-4bab-bef3-870395f50cf1.png)

The python binding does not contain the eCAL Libraries, it just uses whatever you have installed in your system. Are you sure that you don't have residue of prior compilation attempts that are still installed, but binary incompatible?

**Comment by FlorianReimold** [comment]
I also tried to install ecal and the python binding in a qemu based Arm64 chroot environment in Ubuntu 16.04. It did also work, so I guess you are having side effects from another installation.

![qemu](https://user-images.githubusercontent.com/11774314/149934073-0db409a1-89ad-4d31-a169-6eaf6184ed0a.png)

**Comment by FlorianReimold** [comment]
Closing this, as the question seems to be solved. Please reopen, if necessary 😊
