### ISSUE TITLE
[ecalrec]: "/" converts to "\" on Linux

### ISSUE THREAD

**Issue by nilshamacher89** [continental/ecal#475]
**Describe the bug**
using forward slashes in the Meas dir field leads to creation of folders in your home directory which have the same name as the full path including the measurement folders name. The real measurement with it's compartment's is correctly stored at the desired location in `~\home\meas`

**To Reproduce**
start a measurement with the configuration as shown in the first sceenshot.
`$TARGET{OSSELECT WIN "C:\meas" LINUX "/home/continental/meas/"}`
**Expected behavior**
don't create not relevant home-dir flooding empty folders

**Screenshots**
![image](https://user-images.githubusercontent.com/70276837/150318129-65b8ed27-6aaa-4870-bf1c-4d2dd9d93e14.png)
![image](https://user-images.githubusercontent.com/70276837/150317689-acf18071-badb-4133-b070-aea23d4c6761.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.04

**Additional context**

**Comment by FlorianReimold** [comment]
Hi nilshamacher89,

I checked with Windows + Linux VM Setup, where Windows is running eCAL 5.9.1 and Linux (Ubuntu 20.04) eCAL 5.9.2. Everything worked as expected in that setup:

![grafik](https://user-images.githubusercontent.com/11774314/150370064-752b2ceb-1bba-464d-bdb5-bfe5e3b53b48.png)

![grafik](https://user-images.githubusercontent.com/11774314/150370028-619a6b7a-bdb7-401e-ad13-29d1f63ecdff.png)

Which eCAL Version are you using? Can you upload an `.ecalrec` config file that produces that error?

Regards
Florian

**Comment by FlorianReimold** [comment]
Closing, as aparently the directories are not created by eCAL Rec, but by a custom addon that seems to convert `/` to `\` for some reason
