### ISSUE TITLE
Missleading indentation in ecal_mon_plugin_wrapper

### ISSUE THREAD

**Issue by FlorianReimold** [continental/ecal#489]
The line of code is here:
https://github.com/continental/ecal/blob/fe7ba1c266cdfb23b5d28c6c02ac123a0f96e5d2/app/mon/mon_gui/src/plugin/plugin_wrapper.cpp#L124

I guess it is missing curly braces, but I am not sure enough to change it myself

**Comment by Kerstin-Keller** [comment]
Yes, it's missing the curly braces. I think I added the line a few weeks ago (Yep, git blame says so).
Programming to much Python.
This is why we should always have curly braces is `else` statements.
