### ISSUE TITLE
Enable Ninja build on CI for Windows

### ISSUE THREAD

**Issue by Kerstin-Keller** [continental/ecal#505]
The Ninja build system is supposed to be quicker. Plus it will allow to enable buildcache for Windows.

- [x] correct 64bit detection logic to be independent of MSVC in FindScripts
- [x] correctly do delayed loading for npcap.  
- [ ] CSharp Build is not supported by Ninja. Either disable CSharp build or build separately against the previous eCAL "install". (E.g build everything with Ninja and only CSharp binding with MSBuild)
- [ ] Regenerating CMake for the Python builds will most likely not work. Seperate Python build and build against eCAL "install"
- [ ] Cpack doesn't support the nice preset logic 😢 ~Maybe open an issue about it.~ Already open [here](https://gitlab.kitware.com/cmake/cmake/-/issues/23117)

**Comment by FlorianReimold** [comment]
Closing as the test failed. We stick to the ordinary MSVC build for now.
