### ISSUE TITLE
Missing fat-source code in nightly/master version release.

### ISSUE THREAD

**Issue by ZhenshengLee** [continental/ecal#506]
~~Missing code `recycle` in fat-source release package since 5.9.3.~~

**Describe the bug**
Missing the new added thirdparty project code `recycle` in fat-source release package
~~Since version 5.9.3 (not sure, but 5.9.2 is OK)~~
in nightly/master version of eCAL

**To Reproduce**
1. Go to github releases/tags download page
2. download the fat-source
3. untar
4. See there is no `recycle` source in `thirdparty` folder

**Expected behavior**
~~The code can be compiled~~
nightly version of eCAL canbe compiled with fat-source code.

**Screenshots**
![image](https://user-images.githubusercontent.com/17764118/152746842-52a38e60-35e1-43a4-b456-16f7feb897dc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 20.04]

**Additional context**
no.

**Comment by FlorianReimold** [comment]
Hi ZhenshengLee,

What is you exact compile issue? `recycle` is not supposed to be in the 5.9.x fat-source tarballs, as it isn't used in 5.9. It hasn't been included in 5.9.2 as well for the same reason. `recycle` will be relevant for eCAL starting with 5.10. The fat-source packages created for commits on the master branch already include it.

Regards
Florian

**Comment by ZhenshengLee** [comment]
> `recycle` is not supposed to be in the 5.9.x fat-source tarballs, as it isn't used in 5.9. It hasn't been included in 5.9.2 as well for the same reason. `recycle` will be relevant for eCAL starting with 5.10

Oh, I just misunderstood the source code structure of eCAL.

> What is you exact compile issue?

It happens actually in syncing my fork with upstream of eCAL, It should be my reposibiliby to resolve the compiling issues.

> The fat-source packages created for commits on the master branch already include it.

I didn't see a nightly version being published in [release page](https://github.com/continental/ecal/releases), and only see nightly tags and tar without fat-sources [here](https://github.com/continental/ecal/releases/tag/v5.10.0-nightly)
So where should I download the fat-source of this nightly version?

**Comment by FlorianReimold** [comment]
You can access the builds created by the Github Actions by clicking the "Actions" tab. It will bring you here:

https://github.com/continental/ecal/actions

From there you can navigate to whatever branch, commit, workflow etc. you want and download the attached artifacts. The main development branch in eCAL the traditional `master` branch.
