### ISSUE TITLE
Add CMake option to build only cli apps

### ISSUE THREAD

**Issue by brakmic-aleksandar** [continental/ecal#508]
**Is your feature request related to a problem? Please describe.**
If you are using ecal in non-gui enviroment such as Docker container or on server with ssh you don't need to have GUI apps built, since you can't really use them.

**Describe the solution you'd like**
Add CMake option to build only cli apps.

**Describe alternatives you've considered**
Delete GUI apps manually in my Docker containers.

**Comment by rex-schilasky** [comment]
You could just not activate `HAS_QT5` option. Isn't it that simple ?

**Comment by FlorianReimold** [comment]
Well, there is an option to *not* build GUI Apps, so maybe this fits your needs ;)

https://github.com/continental/ecal/blob/91a37298d96843f8cec14eeba9166101ed59862a/CMakeLists.txt#L37

**Comment by brakmic-aleksandar** [comment]
Ooops, my bad, closing this issue.

**Comment by Kerstin-Keller** [comment]
We could thing about renaming this instead.
