### ISSUE TITLE
eCAL_Sub_Receive declaration appears to be incorrect.

### ISSUE THREAD

**Issue by photex** [continental/ecal#51]
Howdy!

https://github.com/continental/ecal/blob/master/ecal/core/include/ecal/cimpl/ecal_subscriber_cimpl.h#L109

I believe that this should declare the `buf_` parameter as `void**` and not `void*`. There isn't a problem calling this and passing a reference to a `void*` in C or C++; but when generating the FFI interface for other languages it's going to cause troubles.
In my case, the code generated by [bindgen](https://rust-lang.github.io/rust-bindgen/) prevented me from using this function. 

I'm happy to submit a PR.

Cheers,
Chip

**Comment by Kerstin-Keller** [comment]
Very cool that you're trying to create a Rust binding!

I agree, that using `void*` is not a very good interface, `char*` or `unsigned char*` would have probably been a better solution, or even `uint8_t` (are these type available in pure C?)

However, we can't just change it to `void**` in this case. First, also the implementation will have to be changed. 
Also the eCAL interface is commited to being stable, changing the type here will most likely cause backward / binary incompatibility issues.
If necessary, we can provide an additional function with the required interface change.

However, the idea is, that the user provides allocated memory of length len, and eCAL will fill that memory with data. So I am not sure if `void**` is necessary?

```
 * @param       handle_       Subscriber handle. 
 * @param [out] buf_          Buffer to store the received message content.
 * @param       buf_len_      Length of the receive buffer or ECAL_ALLOCATE_4ME if
 *                            eCAL should allocate the buffer for you (see eCAL_FreeMem).
 * @param [out] time_         Time from publisher in us.
 * @param       rcv_timeout_  Maximum time before receive operation returns (in milliseconds, -1 means infinite).
```

What exactly are the problems that `bindgen` encounters?

**Comment by photex** [comment]
You're right and I think the problem then is just one particular use-case because it is incorrect to declare it as `void*` when you use the `ECAL_ALLOCATE_4ME` option. Even in C or C++ this will fail to work unless you pass a `void**` which is what the samples and README demonstrates: https://github.com/continental/ecal/blob/master/samples/c/minimal/minimal_rec/src/minimal_rec.c#L41 

The `CopyBuffer` implementation specifically short-circuits if you just pass the null pointer instead of the reference to the null pointer: https://github.com/continental/ecal/blob/master/ecal/core/src/ecalc.cpp#L32

What's the better way to address this then? Since I started the PR I'm happy to continue with another approach.

I'd propose that the best way forward is to remove the ECAL_ALLOCATE_4ME option from this function and add a second function specifically for that case where the caller would like the library to allocate for them.

**Comment by photex** [comment]
According to the big reference: https://en.cppreference.com/w/c/types/integer `uint8_t` should be available even on Windows. 

Also, totally sorry I read your reply on the phone and forget you'd already suggested adding the second function! Is it possible to deprecate ECAL_ALLOCATE_4ME in this function in a stable way?
Maybe log a warning that it will be removed in a future release?

**Comment by Kerstin-Keller** [comment]
Thanks for pointing this out. When used with `ECAL_ALLOCATE_4ME`, references to `void*`, so actually `void**` are passed into the function.

We clearly should not keep it this way, it's not a good design.
But since `void*` means just anything, you can cast it to anything, really.

We will discuss it internally, how to handle the situation.
Since you cannot `deprecate` the function from a compile point of view (the signature won't change), I guess it will be hard to deprectate the usage of `ECAL_ALLOCATE_4ME`. Maybe in some evil ways :wink: preprocessor magic!

How time critical is this issue for you?

**Comment by photex** [comment]
Not time critical at all really. I think the work around is fine while you decide how to proceed. :+1:

I've got rust nodes using publisher and subscribers (both with this function and the callback) and they're all nicely showing up in the monitor and working as expected.

**Comment by Kerstin-Keller** [comment]
> I've got rust nodes using publisher and subscribers (both with this function and the callback) and they're all nicely showing up in the monitor and working as expected.

Ah this is really cool to hear! Let's work together, so that you can contribute this back to this repository such that ecal supports one more programming language!

As you might have noticed, the C-binding is just a wrapper around the C++ interface, which we most commonly use. I don't know Rust well enough, but it might be reasonable to create the Rust binding to target the C++ interface instead of the C interface?

But then, a C binding provides ABI compatibility between compilers and all that, and there might be a reason you used the C interface in the first place :wink:

**Comment by photex** [comment]
Exactly, it's the path of least resistance. But it's not the only way. The ABI issue applies both to C++ and Rust so some kind of interface between has to have an unmangled boundary for it all to work.

The opencv crate uses libclang to generate that boundary, The physx-rs crate also uses something similar. 

Then there is the cxx crate: https://docs.rs/cxx/0.3.4/cxx/

I haven't used it yet but it's on my list of topics to investigate. :D

I'd be more than happy to contribute the Rust bindings directly to this repo, or to the org, if you're interested.

**Comment by rex-schilasky** [comment]
After one week of vacation I stumbled over that very exciting discussion. First of all a Rust binding is highly welcomed. Currently we are finalizing eCAL release 5.6 and right after that we should try to find a gently solution for that function signature issue. To be honest I made that interface and feel some kind of motivation to fix that the right way.

From my point of view we could add two new functions to C API one that can be used with preallocated memory from the caller and another one that can use the "ECAL_ALLOCATE_4ME service" from the core. Finally the new functions will call the "old one" in the 2 different variants and we can remove the old "multi signature" function anyday in a future release.

The new function signatures could look like this ?
```
  /**
   * @brief Receive a message from the publisher in a preallocated buffer.
   *
   * @param       handle_       Subscriber handle. 
   * @param       buf_          Buffer to store the received message content.
   * @param       buf_len_      Length of the receive buffer.
   * @param [out] time_         Time from publisher in us.
   * @param       rcv_timeout_  Maximum time before receive operation returns (in milliseconds, -1 means infinite).
   *
   * @return  Length of received buffer. 
  **/
  ECALC_API int eCAL_Sub_Receive_ToBuffer(ECAL_HANDLE handle_, void* buf_, int buf_len_, long long* time_, int rcv_timeout_);

  /**
   * @brief Receive a message from the publisher and let eCAL allocate the memory.
   *
   * @param       handle_       Subscriber handle. 
   * @param [out] buf_          Buffer to store the pointer to the received message content.
   *                            You need to free the memory finally calling eCAL_FreeMem.
   * @param [out] time_         Time from publisher in us.
   * @param       rcv_timeout_  Maximum time before receive operation returns (in milliseconds, -1 means infinite).
   *
   * @return  Length of received buffer. 
  **/
  ECALC_API int eCAL_Sub_Receive_Alloc(ECAL_HANDLE handle_, void** buf_, long long* time_, int rcv_timeout_);
```

**Comment by Kerstin-Keller** [comment]
## Question 1:

If we make a new signature, do we *have* to keep the `void*` / `void**` one?
Why not go for `char*` or `uint8_t*` (and their `**` equivalents), so something well defined? Where the compiler can actually give you useful warnings if you're doing something stupid...

## Question 2:

> From my point of view we could add two new functions to C API one that can be used with preallocated memory from the caller and another one that can use the "ECAL_ALLOCATE_4ME service" from the core. Finally the new functions will call the "old one" in the 2 different variants and we can remove the old "multi signature" function anyday in a future release.

Actually we should do it the other way round. We introduce the 2 new functions and implement them, and then the old function will use either of the new functions depending on the `ECAL_ALLOCATE_4ME` parameter. Makes it way easier to remove that old function for a new mayor release.

**Comment by rex-schilasky** [comment]
@photex I implemented the two discussed functions in pr #63. What do you mean ?

**Comment by photex** [comment]
This looks great! 👍

**Comment by rex-schilasky** [comment]
Okay, then I will merge that into the current master, close that issue and you can give it a try for your rust binding. Will this binding go open source finally ?
