### ISSUE TITLE
cross-compile with buildroot

### ISSUE THREAD

**Issue by delta-studio** [continental/ecal#511]
Ｉ know this fascinating project from MATLAB EXPO. 

Then speedgoat get communication with x86 linux server by simulink ecal-toolbox.

Now I want cross-compile the eCAL to arm linux v4.14.x with buildroot rootfs.

May some available tutorial for me?

Best regard!

**Comment by hannemn** [comment]
Hello @delta-studio, thanks for your post. We are very happy to hear that you enjoyed the presentation at the MATLAB EXPO last year. At the moment we have unfortunately no explicit tutorial available that shows step-by-step how to cross-compile ecal for another target. The only thing that I can provide you is following link https://github.com/continental/ecal/tree/b13e96c4e3c073e5bc1c88ac51eafbcb9bf75598/testing/contrib/cross to an external contribution. Maybe you can use this as starting point, at least for the toolchain file and some compiler options in the Makefile. I don't know if this helps in your specific use case (probably it will not), but we have also some precompiled arm64/armhf artefacts for ubuntu available that can be found on our ppa repository https://launchpad.net/~ecal/+archive/ubuntu/ecal-latest/+packages.

**Comment by delta-studio** [comment]
Thanks for your reply. **: )**
I'm willing to have a try as above.

**Comment by delta-studio** [comment]
I have succeed in transplanting eCAL to arm embedded linux with buildroot.
The precompiled arm64/armhf artefacts which named *.deb is very useful.
Everything is good now.
Thanks. ：）
