### ISSUE TITLE
Python  MessagePublisher API creation error / documentation incorrect 

### ISSUE THREAD

**Issue by BriFuture** [continental/ecal#514]
Python
the publisher requires topic _desc as `bytes`

```
ecal publisher
class publisher(object):
  """ eCAL publisher """

  def __init__(self, topic_name, topic_type="", topic_desc=b""):
```

The line below 

https://github.com/continental/ecal/blob/6407d9cb68f42402a26b8ddab070bd04b6ecb779/lang/python/core/ecal/core/publisher.py#L28

should be the same as publisher api declares:

```
def __init__(self, name, topic_type="", topic_descriptor=b""):
```

**Comment by rex-schilasky** [comment]
@BriFuture thank you for your report. We will correct the documentation asap.
