### ISSUE TITLE
.desktop Files Have No Category

### ISSUE THREAD

**Issue by Blutkoete** [continental/ecal#520]
**Is your feature request related to a problem? Please describe.**
![eCal_no_category](https://user-images.githubusercontent.com/26028813/154059316-c4722fc6-7201-4e5e-b6a8-e8297846637c.png)

The *.desktop files have no category (Categories=).

**Describe the solution you'd like**
Let's add something, e.g. "Development" or "Network".

**Describe alternatives you've considered**
I can live without it having a category, it just doesn't look nice.

**Additional context**
I'm not sure if Gnome uses categories anymore, so it might not be visible in a plain Ubuntu.

I can possibily create a pull request for this, but the change is very minor.

**Comment by FlorianReimold** [comment]
Nope, modern Gnome dropped those categories. Feel free to create a PR to add them back for Launchers that still use them!

You can find the .desktop files in
`app/xxx/xxx_gui/appmenu/app.desktop.in`
