### ISSUE TITLE
eCAL Play: Display more Information about the channels

### ISSUE THREAD

**Issue by FlorianReimold** [continental/ecal#535]
**Is your feature request related to a problem? Please describe.**
The eCAL Player should be able to display more information about the channels in a measurement than it currently does. At the moment, the workflow is:
- Load eCAL measurment with eCAL Player
- Play it back
- obtain information from the eCAL Monitor

A shortcut for that would be to directly display these information in the player. There could be columns for:

- Type of a channel
- Cummulative size of all messages from a channel
- Frequency
- Timestamp range (maybe in 2 columns with "first timestamp" and "last timestamp")

Ideas for calculating the frequency are:
- `n_frames / meas_length`
- `n_frames / (last_frame_time - first_frame_time)`
- moving window

**Comment by Kerstin-Keller** [comment]
For size / frequency calculation, should we add these to the (higher level) measurement API?
Something like (cached = on demand) read only props?
