### ISSUE TITLE
Traceback Handling in Python Subscriber

### ISSUE THREAD

**Issue by nullket** [continental/ecal#541]
**Is your feature request related to a problem? Please describe.**
When using a python subscriber possible tracebacks (due to exceptions of breaking code) are not printed to stdout/stderr

**Describe the solution you'd like**
A way to get and/or detect tracebacks within python subscriber callbacks 

**Describe alternatives you've considered**
A hostwide log where errors (like tracebacks) are stored

**Additional context**
- I am using `ProtoSubscriber()`
- It also seems like debugging a callback with breaking points in tools like VSCodes is not possible. In this context I would be thankful if you could elaborate the threading/process model of python apps with subscribers and publishers a bit more.

**Comment by Kerstin-Keller** [comment]
Hi @nullket,

I think we've previously hit this issues too.
The thing is, eCAL is using a native threading model. Callbacks are always executed in different threads than the main thread.

Currently, the Python wrapper is implemented in such a way, that the callback thread will try and acquire the GIL, execute the callback, and then again release the GIL.
You can find the code [here] (https://github.com/continental/ecal/blob/854285b737826a58c8b5fc82df8a427acfadc769/lang/python/core/src/ecal_wrap.cxx#L529)
You also have the possibility to continously poll on `sub_receive` instead of registering a callback, you will then receive the data in the main thread.

Publishing, on the other hand, always takes place in the main thread.

I don't know, maybe it's possible to "move" the actual data into the main thread? To synchronize? But unfortunately I have very few experience here, if you have any experience it will be welcome.

**Comment by nullket** [comment]
Hello @nullket thanks for the quick reply. 

Imho it makes totally sense to have each callback being executed in its own thread. In my applications the main is more than often doing other blocking things and would mess with the whole timings it all would run in one thread.  

> You also have the possibility to continuously poll on sub_receive instead of registering a callback

Sure but having the downsides of polling just for the sake tracebacks seems a bit like a bad deal. 

> I don't know, maybe it's possible to "move" the actual data into the main thread? To synchronize? 

To my knowledge this already the default behavior of the regular threading in python. I mean at the end it is just another thread not another process, right? I created very quick python only demo for this (threading like this will acquire the GIL as well):

```python
import threading
import time

class MultiThreadDemo():
    def __init__(self) -> None:
        self.thread_loop_1 = threading.Thread(target=self.async_loop_1, daemon=True)
        self.thread_loop_1.start()
        self.thread_loop_2 = threading.Thread(target=self.async_loop_2, daemon=True)
        self.thread_loop_2.start()

    def async_loop_1(self):
        while True:
            time.sleep(1)
            print("[loop_1]")

    def async_loop_2(self):
        ii = 0
        while True:
            time.sleep(1)
            print("[loop_2]")
            ii += 1
            if ii > 3:
                print("Causing a traceback in loop_2:")
                raise Exception("Artifical Trace")

if __name__ == "__main__":
    demo = MultiThreadDemo()
    while True:
        time.sleep(1)
```
```
/bin/python /tmp/thread.py
[loop_1]
[loop_2]
[loop_1]
[loop_2]
[loop_1]
[loop_2]
[loop_1]
[loop_2]
Causing a traceback in loop_2:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/thread.py", line 24, in async_loop_2
    raise Exception("Artifical Trace")
Exception: Artifical Trace
[loop_1]
[loop_1]
[loop_1]
[loop_1]
```

So the reason might lay in the c++ wrapper? I don't want to start some kind of comparison but ros executes its python callbacks in their own threads as well but tracebacks are visible and logged. Maybe they solved this particular issue already.

**Comment by Kerstin-Keller** [comment]
So I am not 100% sure from what I see, but it seems that ros_py is a pure Python implementation? https://github.com/ros/ros_comm/tree/noetic-devel/clients/rospy/src/rospy/impl 
If there is a C++ (also) a C++ wrapper, and you have the link, I am more than willing to look at it.

Or if you have any other references regarding this topic. Btw I asked a very, very similar question some years back on StackOverflow, but that was regarding [QT Threads](https://stackoverflow.com/questions/29635802/multithreaded-python-application-not-hitting-breakpoints-in-visual-studio).
Maybe you can actually try [this](https://stackoverflow.com/a/3242780/2512608) in your callback.

We'll put in on our agenda, but if it is not an easy fix it might not get highest prio.

**Comment by nullket** [comment]
> So I am not 100% sure from what I see, but it seems that ros_py is a pure Python implementation?

Yes, I just saw this as well. It is all python and therefore uses `threading` which then uses the low-level `_thread` module and this is in c which seems to work with exception hooks.  

> Or if you have any other references regarding this topic.

I am definitely no expert as I have never written a c++ python wrapper/module myself. From a quick research it seems like the whole `pyErr_*()` functions from the [c-API](https://docs.python.org/3/c-api/exceptions.html) are what we are looking for? Just from the documentation it seems like you would regularly check for tracebacks at the end of the callback wrapper with `PyErr_Occurred()` and in case a traceback occurred you would fetch or print it directly with `PyErr_Print()`. [Here](https://stackoverflow.com/questions/1796510/accessing-a-python-traceback-from-the-c-api) is a rather old stackoverflow questions towards this. From my understanding something minimal like following *could* work already:
```
PyObject_CallObject(...)
if (PyErr_Occurred ()) {PyErr_Print ();}
```

On the other hand in your current implementation you are not using the return value of the [PyObject_CallObject()](https://docs.python.org/3/c-api/call.html#c.PyObject_CallObject) call. The return value should be `NULL` in case the call failed. Maybe this would be more efficient than always calling `PyErr_Occurred()` but I am not sure.

> Maybe you can actually try [this](https://stackoverflow.com/a/3242780/2512608) in your callback.

Thanks I will try this out!

**Comment by Kerstin-Keller** [comment]
Thanks for the pointers, we will take a look.

Also I am not sure what is the desired behavior in the whole program in the case of an exception?
Should the programm continue it's execution (which I guess it currently does)? I rather doubt it.

What is the Python behavior if there is an exception in a different thread?

**Comment by nullket** [comment]
> What is the Python behavior if there is an exception in a different thread?

The thread stops as shown in the example above. But in ecal the thread exists after a (successful) callback anyways and a new thread will be created on the next callback, right? 

I do not know what would be best: Having a lot of tracebacks due to callbacks failing or automatically unsubscribing after the first traceback. Somehow I favor more for the first as it gets harder to miss but would no lead to unpredictable behavior (image the callback works sometimes but sometimes not)

**Comment by nullket** [comment]
> From my understanding something minimal like the following could work already:
```
PyObject_CallObject(...)
if (PyErr_Occurred ()) {PyErr_Print();}
```

I just recompiled ecal with this extensions and this works perfectly. Tracebacks are printed to the main window (every time the subscriber executes the callbacks which is perfectly fine for me)
