### ISSUE TITLE
Rec: Remove eCAL::pb linkage

### ISSUE THREAD

**Issue by FlorianReimold** [continental/ecal#546]
On macOS the eCAL Rec GUI Application refuses to start, as it links against:

- `eCAL::pb`
- `eCAL::core` (which also links against `eCAL::pb`)

More Information can be found here: https://github.com/continental/ecal/discussions/537

**Comment by Kerstin-Keller** [comment]
@FlorianReimold you cannot just remove the linkage, as on Windows the ecal::pb symbols are not exported from the eCAL dll.
My option would be, to remove forcing `ecal::pb` as `ecal_add_static_library`. If it's a dynamic library (on systems which want that, e.g. linux and MacOS) the symbols are not contained twice and there is no problem.
