### ISSUE TITLE
A few typos in the documentation

### ISSUE THREAD

**Issue by OrhanKupusoglu** [continental/ecal#559]
While reading the excellent documentation I spotted a few insignificant typos:

https://continental.github.io/ecal/getting_started/hello_world.html
TYPO: **loose**
_So, if your callback needs really long to compute, you may have to decouple your computations to not loose messages._

https://continental.github.io/ecal/applications/rec/recorder_architecture.html
TYPO: **Centraliced**
TYPO: **applicaiton**
_In a Centraliced recording (All topics are recorded over network by just one recorder), this is the only applicaiton you need._

https://continental.github.io/ecal/faq.html
TYPO: **limti**
_When opening a large measurement, this triggers a limti set by the operating system._

https://continental.github.io/ecal/advanced/compatibility.html
TYPO: **Alle**
_Alle eCAL releases sharing the same minor version number can act as drop-in replacements._

https://continental.github.io/ecal/advanced/transport_layers.html
TYPO: **zeroy**
_inner process, zeroy copy communication (pointer forwarding)_

**Comment by FlorianReimold** [comment]
Thanks for pointing those out! I went through the documentation and fixed them 😊
