### ISSUE TITLE
Provide SWIG interface file template for ecalc

### ISSUE THREAD

**Issue by Blutkoete** [continental/ecal#56]
Hello,

not a real issue, more a suggestion.

I created an initial [high-level interface](https://github.com/Blutkoete/golang-ecal) for my personal GO home automation eCAL needs based on a low-level interface auto-generated by [SWIG](http://swig.org). It's not rocket science, but maybe you want to provide an example SWIG i-File with your documentation as it may help people to call eCAL from a wide variety of languages (like Ruby, Lua, Javascript - see "Exits" on their homepage).

The file I used resides [here](https://github.com/Blutkoete/golang-ecal/blob/master/ecalc/ecalc.i). The paths are based on an eCAL installation from the AUR on Arch Linux.

Best regards,

Tobias

**Comment by rex-schilasky** [comment]
Hi Tobias, sorry for the late reply. I checked your golang repository and for sure it's a great idea to provide and maintain a SWIG interface file together with ecal. We check how to do it the best way and will add it in the next releases.

**Comment by rex-schilasky** [comment]
@Blutkoete: I will close this issue for now. We keep this idea in mind but currently we are focusing on other tasks.
