### ISSUE TITLE
Dependencies for Linux build

### ISSUE THREAD

**Issue by gmnvh** [continental/ecal#6]
I am trying to compile ecal for my Linux Ubuntu 18.04.2 but I am facing some dependencies issues.

First I had issues with Asio and tclap but both were fixed using:

`sudo apt-get install libasio-dev`

`sudo apt-get install libtclap-dev`

Now I am having issues with simpleini:

```
/usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 
(message):
   Could NOT find simpleini (missing: simpleini_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 
(_FPHSA_FAILURE_MESSAGE)
   cmake/find_scripts/Findsimpleini.cmake:17 
(find_package_handle_standard_args)
   CMakeLists.txt:77 (_find_package)
   contrib/ecaltime/linuxptp/src/CMakeLists.txt:19 (find_package)


-- Configuring incomplete, errors occurred!
```

I tried installing `liubinih-dev` but I am still having the same issue.

What would be the best way to fix this dependency? I saw that there is a GitHub project at [https://github.com/brofield/simpleini](url). Should I use this one? Can this dependencies be added to the README file?

**Comment by rex-schilasky** [comment]
Hi @gmnvh, did you checkout the repositories recursively ?

```git clone --recursive https://github.com/continental/ecal.git```

**Comment by gmnvh** [comment]
No, I did not. I actually downloaded the repository as a ZIP file.
Cloning properly as you suggested, the command `cmake .. -DCMAKE_BUILD_TYPE=Release` works fine.

But now, trying the `make -j` I got error too (Sorry about these basic questions. Linux setup is new for me). It may be related to the `libasio-dev` library I installed. Should I uninstall it? What version am I suppose to use?

```
/home/ros/cnx/ecal/rep/ecal/ecal/core/src/io/udp_receiver.cpp: At global
scope:
/home/ros/cnx/ecal/rep/ecal/ecal/core/src/io/udp_receiver.cpp:142:51: 
error: ‘chrono’ in namespace ‘asio’ does not name a type
    void CUDPReceiverImpl::RunIOContext(const
asio::chrono::steady_clock::duration& timeout)
                                                    ^~~~~~
/home/ros/cnx/ecal/rep/ecal/ecal/core/src/io/udp_receiver.cpp:142:71: 
error: expected unqualified-id before ‘::’ token
    void CUDPReceiverImpl::RunIOContext(const
asio::chrono::steady_clock::duration& timeout) ^~
/home/ros/cnx/ecal/rep/ecal/ecal/core/src/io/udp_receiver.cpp:142:71: 
error: expected ‘)’ before ‘::’ token
/home/ros/cnx/ecal/rep/ecal/ecal/core/src/io/udp_receiver.cpp:142:71: 
error: expected initializer before ‘::’ token
ecal/core/src/CMakeFiles/core.dir/build.make:230: recipe for target 'ecal/core/src/CMakeFiles/core.dir/io/udp_sender.cpp.o' failed
make[2]: *** [ecal/core/src/CMakeFiles/core.dir/io/udp_sender.cpp.o] Error 1
```

**Comment by Kerstin-Keller** [comment]
I suspect that CMake now finds the sytem version of asio. For Ubuntu 18.04 this is version 1.10.8, however eCAL requires asio > 1.12.

I recommend uninstalling the system packages, and also doing a complete new build (including removing all generated CMake files).

**Comment by gmnvh** [comment]
I removed the packages:
`sudo apt-get --purge remove libasio-dev`
`sudo apt-get --purge remove libtclap-dev`

Deleted the `_build` folder and then the sequence in the README file works:

```
mkdir _build
cd _build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j
cpack -G DEB
sudo dpkg -i eCAL*
```

Thanks very much for all the support !!! :)

**Comment by rex-schilasky** [comment]
Perfect :)
