### ISSUE TITLE
Change some return types of new `Config` function

### ISSUE THREAD

**Issue by KerstinKeller** [continental/ecal#604]
**Is your feature request related to a problem? Please describe.**
Some of the return types of the new Config functions (`GetMemfileMinsizeBytes`, `GetMemfileBufferCount`, ...) have int return types, but in the usage, they are always cast to `size_t`.

The log filter functions, e.g. `GetConsoleLogFilter` return a `std::string`, although they are actually a list of filters. Should they instead return a `std::vector<std::string>` (or actually maybe a set `std::set` would be even more appropriate)

**Describe the solution you'd like**
Discuss what are proper return types so that logic can be moved to the config functions, not the user code.

We should discuss this before a 5.10 freeze where these functions will become part of the public API.

**Comment by FlorianReimold** [comment]
- keep `int` as `int` (no `size_t` converstion to keep the ability to transport special information in magic numbers)
- Parse lists as good as possible and return values from the eCAL API (applies to log-filters)
- return regexp as raw string

**Comment by Kerstin-Keller** [comment]
See #614.
- `size_t` was used in instances where it is "always" casted, other occurences keep int
- the logs return a filter mask, denoted at least with a typedef, to indicated it's a filter, not a regular `char` (even though it's not typesafe.

**Comment by FlorianReimold** [comment]
Fixed by #614
