### ISSUE TITLE
Add a flag to the Build-on-Linux documentation to honour default system configuration directory

### ISSUE THREAD

**Issue by Blutkoete** [continental/ecal#66]
Hello,

while dockerizing eCAL for my home use, I noticed that DEB package actually puts ecal.ini and ecaltime.ini under /usr/etc/ (and make install puts it under /usr/local/etc). I do not care so much about /usr/local, but maybe it's a nice idea for known so Linux-savy users to add the "-DCMAKE_INSTALL_SYSCONFDIR=/etc" to the cmake command in the documentation or at least add a comment about that so that the resulting DEB package from cpack will put the configuration files to a more intuitive location.

I will also add that flag to the AUR Arch Linux package instead of moving the config files around before packaging like I currently do.

Thank you for your work!

**Comment by FlorianReimold** [comment]
I added the flag to our own github actions files (PR #137), so the eCAL 5.8 artifacts built by us for Ubuntu will place their config files in `/etc/ecal`. eCAL 5.8 will also properly install in multiarch lib dirs, which is standard at least for debian based distributions.
I am not sure about the documentation though, I think it might actually distract to have more cmake options listed there, especially when they don't really contribute to building eCAL...

**Comment by Blutkoete** [comment]
Thank you very much! I agree that adding it to the documentation will distract the reader from the flags which have a direct impact on eCAL.
