### ISSUE TITLE
HDF5Meas cannot be copied

### ISSUE THREAD

**Issue by ZobyTwo** [continental/ecal#692]
**Describe the bug**
HDF5Meas has a copy constructor, which duplicates the internal impl-pointer, leading to dereferencing a dangling pointer when the instances get destroyed.

**To Reproduce**
1. Create HDF5Meas instance.
2. Copy HDF5Meas instance.
3. Compile and run the program (with sanitizers).

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS: Ubuntu.
 - Version 20.04.

**Comment by Kerstin-Keller** [comment]
What is your usecase for copying the measurement? For reading or writing?
I'd argue that we should delete any copy (move?) operators, they don't really make sense in the measurement case. (Publishers / Subscribers are non-copyable, too).

**Comment by ZobyTwo** [comment]
My use-case is that I created them in a function and returned them by copy. When the function's temporary got deleted, this broke the value that arrived at the call-side as well.

Deleting copy makes sense.
Deleting move (or setting the moved-from member to nullptr) would work as well as the class appears to have the required nullptr checks (I did not check it too closely).

I guess you could also wrap the impl-pointer in a std::unique_ptr, which should give you nice semantics automatically.

**Comment by Kerstin-Keller** [comment]
Thanks again for this issue. Internal member is now a `unique_ptr`, and move construction / assignment is forbidden.
Thanks for reporting!
