### ISSUE TITLE
Correct version numbering when builind the release tar.gz (or zip) file

### ISSUE THREAD

**Issue by Blutkoete** [continental/ecal#7]
Hello,

I'm currently creating an Arch Linux AUR package for eCal and there is only one minor nitpick left. I download the tagged release, patch it with the my compile-on-Arch-Linux patch, and then build from there. But as I'm not building from within a Git repository, the version detection in CMakeLists.txt fails and all my .so files end up with version 0.0.0.

This is not a showstopper as I can either patch or sed the CMakeLists.txt myself, but I think it would be nice in general if version detection would also work when building outside of a Git clone.

**Comment by rex-schilasky** [comment]
We know that "issue" and think about a fall back strategy in the case of that kind of Git isolated build.

**Comment by Blutkoete** [comment]
Thank you.

I'm using sed for now to put the version string directly into the CMakeLists.txt, so my AUR package is covered, but I'm looking forward to having a solution that feels less hackish.

Keep up the good work!

**Comment by rex-schilasky** [comment]
Possible solution to complicated. Please checkout repository instead of using a tar.gz archive if you need a correct version number.
