### ISSUE TITLE
eCAL monitor and protobuf messages

### ISSUE THREAD

**Issue by AlexDaniel** [continental/ecal#702]
**Is your feature request related to a problem? Please describe.**

I'm running a [rust demo](https://github.com/kopernikusauto/ecal-rs/tree/main/demo), and with some tweaks it works fine. However, when I look at the data in eCAL Monitor, it gives me an error like this:
```
2022-07-03 00:17:51.624	Error	eCALMon	Error when receiving data on topic "/kpns/demo/pong": CDynamicSubscriber: Could not get description for topic /kpns/demo/pong
```
I guess this is totally understandable because protobuf description wasn't provided. But… how can I add it?

I guess this is also related to the fact that [Hello World with protobuf (Python)](https://continental.github.io/ecal/getting_started/hello_world_python_proto.html) page is not provided. If it was, I think it'd run into the same problem (or document a solution for it).

I have a feeling that an answer to my question involves recompiling eCAL Monitor, but then I don't really understand the idea of having prebuilt packages for it given that it is only usable for strings…

Am I missing something?

**Describe the solution you'd like**
Ideally it should be possible to add protobuf descriptions to eCAL Monitor (e.g. via drag'n'drop or by providing a path to a folder).

**Comment by rex-schilasky** [comment]
Hi @AlexDaniel,

eCAL Monitor is a generic tool that doesn't need to be recompiled for specific message types. It has so called reflection plugins for different message formats onboard. All these plugins use the same kind of technique to give you a live data preview:

- eCAL publisher provides message name, message type, message desriptor
- eCAL Monitor checks (after selecting a specific message) is there
  - a generic pluginin for that message family (like protobuf)
  - and or a specific plugin for that message sub type (like a image / radar visualization for example)
- for generic reflection eCAL takes the message type and descriptor and tries to do a reflection if available for that message format (for google protobuf it is, but this is bad documented stuff from google) to get the content of the message dynamically
- type and descriptors are transferred to from the publisher to all matching subscribers (and so the monitor) independent from the payload on a another layer (udp)

If an eCAL language binding does not provide these descriptors, there is no way to do a dynamic message decoding. As far as I know the Rust binding can not extract this descriptor from the protobuf RUST API unfortunately, see [here](https://github.com/kopernikusauto/ecal-rs/blob/5fdc9e101f7df119111f2fdef809f77a478218a0/src/lib.rs#L154).

For python it works as a charm, just start the [person python publisher](https://github.com/continental/ecal/blob/master/samples/python/person_snd/person_snd.py) and you will see the message dynamic encoding in the eCAL Monitor. It's not documented right now in the docs but will be soon hopefully.

**Comment by AlexDaniel** [comment]
@rex-schilasky, ah, OK! Thank you very much for your answer! So, basically, yes, the description is needed but ecal nodes should be able to provide them, the problem is the rust binding which currently doesn't. That makes things a lot clearer, thank you!

Feel free to close this ticket. I think the only issue is that maybe this behavior should be mentioned in the docs (and that missing python protobuf page should be written, I guess). But I got my answers so no issue from my side anymore!
