### ISSUE TITLE
eCAL SHM communication broken for Process after hibernate

### ISSUE THREAD

**Issue by Kerstin-Keller** [continental/ecal#714]
**Describe the bug**
After returning from hibernate, eCAL Subscribers are not working anymore.

**Analysis**
After a hibernate, the `CMemFileObserver::Observe` times out, the state is set to not obeserving.
https://github.com/continental/ecal/blob/0e714c6342d97f8a1c8c91bf299dbf7208e46176/ecal/core/src/io/ecal_memfile_pool.cpp#L274

This condition can never be rehabilitated.
The observer object for the memfile is global, and ist only deleted upon closing the proces..
Thus once the communication has timed out, it will never start again.

**Comment by rex-schilasky** [comment]
There is a Memory Pool cleanup function

https://github.com/continental/ecal/blob/0e714c6342d97f8a1c8c91bf299dbf7208e46176/ecal/core/src/io/ecal_memfile_pool.h#L90

that needs to be called cyclic but is not used currently.
