### ISSUE TITLE
Add support for QNX operating system  

### ISSUE THREAD

**Issue by hannemn** [continental/ecal#80]
In order to compile eCAL with qcc properly, some fixes and workarounds has to be applied to the source code and CMake configuration.

**Comment by leo07046219** [comment]
hello hannemn, 
I foundd ecal in github few days ago,It may be a communication middleware choice to build my embedded system software framwork.
I hava few questions looking forward to your answers.
1.what is the original purpose for the ecal?
2.why ecal does not support 32bit platform? Do you have plan to support?
3.do you have support plan for other embedded platform?
Thanks!

**Comment by hannemn** [comment]
Hello @leo07046219, thanks for your questions. And I'm glad to hear that you maybe decide to use eCAL for your emdedded system software framework.

Regarding question no. 1: 
Originally eCAL was developed to communicate between distributed high performance/data algorithms on one ore more computing nodes as rapid prototyping middleware framework. But we had certain requirements to our algorithm system, that currently no other middleware layer software can fulfil at the same time. The challenge was for example to send large messages like point clouds, camera images or just high-frequency messages in a publish-subscriber network without having message drops or a high jitter. At the same time we wanted to record the data traffic for a later replay or post processing analysis. And furthermore everything should work on Windows and Linux.
These led to following design goals: a low latency and high-data troughput (usage of shared memory) publish-subscriber layer,  compatiblity on multiple operation systems and architectures, tools for monitoring/replaying/recording data, a lightweight and comprehensible C++ API, language bindings, replaceable serialization protocol, and much more...

Regarding question no. 2:
eCAL supports 32bit platforms, but only if you build it from source. [(see documentation)](https://continental.github.io/ecal/development/building_ecal_from_source.html)  Since most of our users have 64 bit operating systems, we only ship binary installer for that.

Regarding question no. 3:
Currently we have no official roadmap for supporting embedded devices. But you can build eCAL from source of course, in order to create a custom installer for your embedded device, which should work out-of-the-box. eCAL was successfully tested already on various platforms (arm64, x86) and operating systems (Windows and all posix OSs like linux, freebsd, macOS, QNX, ..).

**Comment by leo07046219** [comment]
Thanks for your answer @hannemn 

Just call me Leo,haha

1.what detail background knowledge! 
The design goal is  promising: a  - perfect c++ compatible,multi-OS supported,efficient and easy to 
 use - middleware.
Does eCAL have already be used in some commerical product? If the answer it not confidential.

2.ok, I may try sometime. 

3.eCAL was successfully tested already on various platforms (arm64, x86) ~ what about arm32?
Our product various from 32bit to 64bit，from x86 to arm(other platform).So, I my embedded framework is not just so embedded, accurately, is a "all"-platform-framwork.

4.Does the server/client mode in eCAL can support  1-server--N-client communication？the demo in the clientserver_test is 2 1-server--1-client.

5.Build a framework,is not a easy way, We don't want to write all components, the choosing of the communicating middleware is now troubling me.The requement is pub-sub,Point2Point(request-response),  platform&OS compatible.Do you have some suggestions？

Thanks.

**Comment by FlorianReimold** [comment]
Hey Leo,

1. We use eCAL internally for rapid prototyping, as it enables us to quickly change components (other applications, more or less PCs, different OS) and lets us record and replay data for debugging.

3. I don’t know of any platform we use that still has a 32bit arm processor in it. But at least for Ubuntu armhf (32bit arm hard float) it compiles just fine. You can check out [this Ubuntu PPA]( https://launchpad.net/~ecal/+archive/ubuntu/ecal-latest), which contains builds for i386, amd64, armhf and arm64.

4. eCAL Communication is brokerless, so there is no server. Just publishers and subscribers. Those connect N->N. The eCAL Services (request-response pattern) can also be called from any client.

**Comment by leo07046219** [comment]
@FlorianReimold  
Thanks for your response.
I may try to build  the src for 32 bit embedded platform.

**Comment by hannemn** [comment]
Basic support for QNX has been added with #182 .
